INSERT INTO public.market_leads (
  company_name,
  sector,
  target_segment,
  hq_country,
  hq_city,
  website,
  contact_url,
  signal_title,
  signal_summary,
  signal_source_url,
  signal_date,
  priority_score,
  offer_angle,
  next_action,
  lead_status,
  notes
)
VALUES
  ('Manutan','B2B ecommerce','ETI and Enterprise','France','Gonesse','https://www.manutan.com','https://www.manutan.com/fr/accueil/contact','Manutan automated product data management with AI','Recent AI deployment in core catalog workflows suggests clear upskilling and change-management needs.','https://www.manutan.com/fr/accueil/presse/actualites/2025/manutan-automatise-la-gestion-de-ses-references-produits-grace-a-lia','2025-02-05',88,'AI adoption academy for operations and procurement teams','Reach out with a 4-week pilot focused on catalog and workflow teams.','new','Strong fit: mid-enterprise B2B with practical AI use cases.'),
  ('Renault Group','Automotive','Enterprise','France','Boulogne-Billancourt','https://www.renaultgroup.com','https://www.renaultgroup.com/contact/','Renault Group Future Ready strategy with AI components','Enterprise-wide transformation indicates recurring needs for AI enablement at team level.','https://www.renaultgroup.com/actualites/finance/renault-group-future-ready-plan/',NULL,84,'Business-unit AI playbooks for manufacturing and support functions','Target one business unit with AI training + process redesign sprint.','new','Large account; longer sales cycle but high ACV.'),
  ('Danone','FMCG','Enterprise','France','Paris','https://www.danone.com','https://www.danone.com/contact-us.html','Danone and Microsoft partnership to scale AI','Scaling AI across a global company creates demand for practical team adoption programs.','https://www.danone.com/press-releases-list/danone-and-microsoft-join-forces-to-advance-ai-across-the-company.html','2025-06-18',86,'AI enablement track for supply chain and corporate teams','Pitch adoption governance + KPI-based learning roadmap.','new','High potential if positioned with measurable business outcomes.'),
  ('Veolia','Utilities and environmental services','Enterprise','France','Aubervilliers','https://www.veolia.com','https://www.veolia.com/fr/contact','Veolia and IBM acceleration of digital transformation','Digital transformation narrative indicates ongoing AI capability rollout opportunities.','https://www.veolia.com/fr/groupe/medias/communiques-presse/veolia-ibm-acceleration-transformation-digitale','2025-02-05',83,'Field-operations AI training and management coaching','Lead with operational excellence and risk-aware AI adoption modules.','new','Operationally complex org; emphasize safety and compliance.'),
  ('SNCF Group','Mobility and rail','Enterprise','France','Saint-Denis','https://www.sncf.com','https://www.sncf.com/fr/groupe/contact','SNCF communication on generative AI','Public positioning on gen AI implies internal demand for structured onboarding of teams.','https://www.sncf.com/fr/groupe/newsroom/ia-generative','2025-05-20',79,'GenAI literacy plus workflow integration for transport operations','Propose pilot with support and back-office teams.','new','Public-sector style buying process; expect longer validation.'),
  ('La Poste Groupe','Postal and logistics services','Enterprise','France','Paris','https://www.lapostegroupe.com','https://www.lapostegroupe.com/fr/contactez-nous','La Poste framework for trusted AI','Trust-centered AI strategy aligns with governance and adoption training offers.','https://www.lapostegroupe.com/fr/actualite/intelligence-artificielle-confiance',NULL,80,'Responsible AI program for managerial and operational staff','Open with compliance-first AI deployment workshops.','new','Good fit for trust/governance positioning.'),
  ('Docaposte','Digital trust and IT services','Enterprise','France','Ivry-sur-Seine','https://www.docaposte.com','https://www.docaposte.com/contact','Docaposte highlights AI against fraud use cases','Applied AI use case indicates room for function-specific training and scaling support.','https://www.docaposte.com/blog/confiance-numerique/comment-lia-generative-renforce-les-solutions-fraude',NULL,77,'Use-case academy for fraud, ops, and support teams','Position as acceleration layer after first AI projects.','new','Can also become a distribution partner.'),
  ('Orange','Telecom','Enterprise','France','Issy-les-Moulineaux','https://www.orange.com','https://www.orange.com/fr/contact','Orange highlights AI and data in strategic communication','Strong AI narrative suggests continuous need to onboard non-technical teams.','https://hellofuture.orange.com/fr/ia-et-analyse-de-donnees/','2025-10-04',78,'Cross-functional AI adoption for customer and network teams','Target one region or entity for a measurable pilot.','new','Large account and complex procurement.'),
  ('BNP Paribas','Banking','Enterprise','France','Paris','https://group.bnpparibas','https://group.bnpparibas/en/group/contact-us','BNP Paribas principles for responsible generative AI','Responsible AI framing matches governance + adoption offerings.','https://group.bnpparibas/en/our-commitments/responsible-business/principles-for-a-responsible-use-of-generative-ai/',NULL,75,'Risk-aware AI adoption framework for business teams','Start from compliance and productivity wins in support functions.','new','Decision cycle can be long; focus on one division.'),
  ('Societe Generale','Banking','Enterprise','France','Paris','https://www.societegenerale.com','https://www.societegenerale.com/en/contact-us','Societe Generale job posting for conversational AI data scientist','Active hiring for AI capabilities signals organizational demand for broader upskilling.','https://careers.societegenerale.com/en/job-offers/data-scientist-conversational-ai-boursorama-h-f-24000QN7-en','2025-09-18',76,'AI capability uplift for customer-facing and support teams','Approach through innovation and HR learning contacts.','new','Use hiring signal as conversation opener.'),
  ('Credit Agricole CIB','Banking','Enterprise','France','Montrouge','https://www.ca-cib.com','https://www.ca-cib.com/contact-us','CA CIB role focused on generative AI and ML','Hiring around gen AI indicates immediate adoption and capability scaling needs.','https://jobs.ca-cib.com/offre-de-emploi/emploi-cdd-ml-engineer-focus-on-generative-ai-h-f_12491.aspx',NULL,74,'GenAI rollout support for business and control functions','Lead with governance + productivity blend.','new','Corporate banking context values risk control messaging.'),
  ('LCL','Banking','Enterprise','France','Villejuif','https://www.lcl.fr','https://www.lcl.fr/contact','LCL appears in Credit Agricole AI-related hiring context','Bank unit likely needs team-level AI enablement aligned with group strategy.','https://groupecreditagricole.jobs/fr/nos-offres?search=lcl','2026-02-25',72,'Department-level AI training tied to workflow KPIs','Target operations and client support departments.','new','Entity-level entry point may be easier than full group deal.'),
  ('AXA','Insurance','Enterprise','France','Paris','https://www.axa.com','https://www.axa.com/en/contact-us','AXA communication on AI opportunities risks and governance','Clear focus on AI governance supports adoption + policy training offers.','https://www.axa.com/en/magazine/artificial-intelligence-opportunities-risks-and-governance','2024-12-02',74,'Responsible AI deployment for insurance teams','Open with AI governance diagnostic workshop.','new','Insurance buyers prioritize risk controls and auditability.'),
  ('VINCI','Construction and infrastructure','Enterprise','France','Nanterre','https://www.vinci.com','https://www.vinci.com/vinci.nsf/en/contact/pages/index.htm','VINCI publication on AI adoption boundaries and change','Change-management angle fits practical AI training for operational teams.','https://www.vinci.com/vinci.nsf/en/news-update/pages/artificial_intelligence_at_vinci_overcoming_resistance_to_change_while_setting_clear_boundaries_072024.htm','2024-07-01',73,'AI change-management training for field and project teams','Pitch adoption framework with frontline use cases.','new','Good fit if tied to productivity and safety metrics.'),
  ('Thales','Defense and aerospace','Enterprise','France','Meudon','https://www.thalesgroup.com','https://www.thalesgroup.com/en/contact-us','Thales communication around AI at group level','Mature AI environment still requires broad business adoption programs.','https://www.thalesgroup.com/en/group/journalist/ai-thales',NULL,71,'AI literacy for non-technical business units','Target one corporate function before scaling.','new','Highly structured procurement and security constraints.'),
  ('ENGIE (Tractebel)','Energy and engineering','Enterprise','France','Courbevoie','https://www.engie.com','https://www.engie.com/en/contact-us','ENGIE hiring internship focused on AI for information systems','Hiring signal suggests active AI projects and demand for adoption support.','https://jobs.engie.com/job/Courbevoie-STAGE-Intelligence-Artificielle-Syst%C3%A8me-d%27information-HF-92400/1175226001/','2025-11-17',72,'AI onboarding for engineering and support teams','Use talent and change pressure as urgency trigger.','new','Entry through one engineering entity can reduce sales friction.'),
  ('Michelin','Industrial manufacturing','Enterprise','France','Clermont-Ferrand','https://www.michelin.com','https://www.michelin.com/en/contact-us/','Michelin narrative on AI serving people and performance','Manufacturing AI messaging aligns with structured upskilling offers.','https://www.michelin.com/en/innovation/artificial-intelligence-at-the-service-of-humanity/',NULL,72,'AI training linked to plant and supply-chain performance','Propose a plant-focused pilot with measurable KPIs.','new','Industrial context needs concrete ROI framing.'),
  ('Carrefour','Retail','Enterprise','France','Massy','https://www.carrefour.com','https://www.carrefour.com/en/contact-us','Carrefour launched data and retail media platform','Data-centric strategic move creates AI adoption opportunities in commercial teams.','https://www.carrefour.com/en/newsroom/carrefour-launches-carrefour-links-its-new-data-retail-media-platform',NULL,74,'AI enablement for merchandising and marketing teams','Pitch AI for pricing, assortment, and campaign operations.','new','Retail needs short-cycle visible wins.'),
  ('Saint-Gobain','Construction materials','Enterprise','France','Courbevoie','https://www.saint-gobain.com','https://www.saint-gobain.com/en/contact-us','Saint-Gobain innovation strategy includes digitalization','Digitalization strategy indicates demand for adoption across multiple functions.','https://www.saint-gobain.com/en/news/our-innovation-strategy-driving-growth-through-sustainability-and-digitalization',NULL,69,'AI adoption playbook for industrial and support teams','Start with one country unit and replicate.','new','Signal is broader digitalization; qualify AI budget early.'),
  ('XEFI','IT services','SMB and Mid-market','France','Rillieux-la-Pape','https://www.xefi.com','https://www.xefi.com/contact','XEFI hiring on AI-related profile','IT services actor can be both client and channel for broader SME rollout.','https://carriere.xefi.fr/front-jobs-detail.html?id_job=13043&id_origin=0',NULL,81,'Partner-enabled AI training for SME customers','Approach as both direct account and reseller channel.','new','High leverage if partner model is accepted.'),
  ('Keolis','Mobility services','Enterprise','France','Paris','https://www.keolis.com','https://www.keolis.com/en/contact','Keolis content on generative AI in operations','Mobility operator use cases fit AI enablement programs for support functions.','https://www.keolis.com/fr/medias/actualites/ia-generative',NULL,70,'Operational AI training with governance baseline','Propose quick diagnostic plus targeted training cohorts.','new','Transit operators need practical and compliant use cases.'),
  ('Teleperformance','BPO and customer operations','Enterprise','France','Paris','https://www.teleperformance.com','https://www.teleperformance.com/en-us/contact-us','External coverage on AI impact in call-center operations','High disruption pressure in BPO makes adoption and re-skilling urgent.','https://www.lemonde.fr/economie/article/2024/03/29/teleperformance-geant-des-centres-d-appels-face-au-vertige-de-l-intelligence-artificielle_6224792_3234.html','2024-03-29',76,'AI transition program for customer-service managers and agents','Lead with workforce transition and productivity positioning.','new','Source is press coverage; validate internal sponsor early.')
ON CONFLICT (company_name, signal_source_url) DO NOTHING;

-- Baseline classification so leads are immediately sortable for prospecting.
UPDATE public.market_leads
SET
  icp_fit_score = COALESCE(icp_fit_score, priority_score),
  buying_intent_score = COALESCE(
    buying_intent_score,
    GREATEST(0, LEAST(100, priority_score - 5))
  ),
  ease_of_access_score = COALESCE(
    ease_of_access_score,
    CASE
      WHEN target_segment = 'SMB and Mid-market' THEN 75
      ELSE 55
    END
  ),
  lead_temperature = CASE
    WHEN priority_score >= 82 THEN 'hot'
    WHEN priority_score >= 70 THEN 'warm'
    ELSE 'cold'
  END,
  pipeline_stage = COALESCE(pipeline_stage, 'sourced'),
  enrichment_status = CASE
    WHEN decision_maker_name IS NOT NULL THEN 'done'
    ELSE enrichment_status
  END;

-- High-confidence public emails extracted from official contact pages.
UPDATE public.market_leads
SET
  contact_email = 'contact@renaultgroup.com',
  preferred_channel = 'email',
  enrichment_status = 'in_progress'
WHERE company_name = 'Renault Group';

UPDATE public.market_leads
SET
  contact_email = 'contact@xefi.com',
  preferred_channel = 'email',
  enrichment_status = 'in_progress'
WHERE company_name = 'XEFI';

INSERT INTO public.market_leads (
  company_name, sector, target_segment, hq_country, hq_city,
  website, contact_url, signal_title, signal_summary, signal_source_url,
  signal_date, priority_score, offer_angle, next_action, lead_status, notes,
  icp_fit_score, buying_intent_score, ease_of_access_score, lead_temperature,
  pipeline_stage, enrichment_status, owner_name, decision_maker_name,
  decision_maker_title, decision_maker_linkedin_url, contact_email, contact_phone,
  preferred_channel, last_contacted_at, next_follow_up_at
)
VALUES
('13 Productions', 'Professional services and software', 'SMB and Mid-market', 'France', NULL, 'https://www.13prods.fr', 'https://www.13prods.fr/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.13prods.fr/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q78523517 and verified on https://www.13prods.fr/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@13prods.fr', NULL, 'email', NULL, NULL),
('Action Audio', 'Professional services and software', 'SMB and Mid-market', 'Unknown', NULL, 'https://action-audio.com', 'https://action-audio.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://action-audio.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q110653577 and verified on https://action-audio.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@action-audio.com', NULL, 'email', NULL, NULL),
('Arthur Bryant''s', 'Professional services and software', 'SMB and Mid-market', 'United States', NULL, 'http://www.arthurbryantsbbq.com', 'http://www.arthurbryantsbbq.com', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'http://www.arthurbryantsbbq.com', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q4798120 and verified on http://www.arthurbryantsbbq.com.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@arthurbryantsbbq.com', NULL, 'email', NULL, NULL),
('As Talents', 'Professional services and software', 'SMB and Mid-market', 'France', NULL, 'https://www.astalents.fr', 'https://www.astalents.fr/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.astalents.fr/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q111547599 and verified on https://www.astalents.fr/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@astalents.fr', NULL, 'email', NULL, NULL),
('Auvergne-Rhône-Alpes Cinéma', 'Professional services and software', 'SMB and Mid-market', 'France', NULL, 'http://www.auvergnerhonealpes-cinema.fr', 'http://www.auvergnerhonealpes-cinema.fr/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'http://www.auvergnerhonealpes-cinema.fr/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q3429960 and verified on http://www.auvergnerhonealpes-cinema.fr/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@auvergnerhonealpes-cinema.fr', NULL, 'email', NULL, NULL),
('BrainWorks', 'Professional services and software', 'SMB and Mid-market', 'France', NULL, 'http://brainworks.tv', 'http://brainworks.tv/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'http://brainworks.tv/contact', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q121083183 and verified on http://brainworks.tv/contact.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@brainworks.tv', NULL, 'email', NULL, NULL),
('Champagne Quatresols-Gauthier', 'Professional services and software', 'SMB and Mid-market', 'France', NULL, 'http://www.champagne-quatresols-gauthier.com', 'http://www.champagne-quatresols-gauthier.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'http://www.champagne-quatresols-gauthier.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q109480484 and verified on http://www.champagne-quatresols-gauthier.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@champagne-quatresols-gauthier.com', NULL, 'email', NULL, NULL),
('coopérative d''habitation des Moulins', 'Professional services and software', 'SMB and Mid-market', 'Switzerland', NULL, 'https://www.cooperativedesmoulins.ch', 'https://www.cooperativedesmoulins.ch/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.cooperativedesmoulins.ch/contact-us', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q133284236 and verified on https://www.cooperativedesmoulins.ch/contact-us.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@cooperativedesmoulins.ch', NULL, 'email', NULL, NULL),
('coopérative d’habitation du Chablais', 'Professional services and software', 'SMB and Mid-market', 'Switzerland', NULL, 'https://www.cohacha.ch', 'https://www.cohacha.ch/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.cohacha.ch/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q133054540 and verified on https://www.cohacha.ch/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@cohacha.ch', NULL, 'email', NULL, NULL),
('Federal Planning Bureau', 'Professional services and software', 'SMB and Mid-market', 'Belgium', NULL, 'https://www.plan.be', 'https://www.plan.be', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.plan.be/contact', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q2181235 and verified on https://www.plan.be/contact.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@plan.be', NULL, 'email', NULL, NULL),
('Graphis', 'Professional services and software', 'SMB and Mid-market', 'Switzerland', NULL, 'https://www.graphis.ch', 'https://www.graphis.ch', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.graphis.ch', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q133282940 and verified on https://www.graphis.ch.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@graphis.ch', NULL, 'email', NULL, NULL),
('Inkas Film Production', 'Professional services and software', 'SMB and Mid-market', 'Greece', NULL, 'https://www.inkasfilms.com', 'https://www.inkasfilms.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.inkasfilms.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q110822911 and verified on https://www.inkasfilms.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@inkasfilms.com', NULL, 'email', NULL, NULL),
('La Fabrique au Burkina Faso', 'Professional services and software', 'SMB and Mid-market', 'Burkina Faso', NULL, 'https://www.lafabrique-bf.com', 'https://www.lafabrique-bf.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.lafabrique-bf.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q136377597 and verified on https://www.lafabrique-bf.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@lafabrique-bf.com', NULL, 'email', NULL, NULL),
('Le Faham', 'Professional services and software', 'SMB and Mid-market', 'France', NULL, 'https://lefaham.com', 'https://lefaham.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://lefaham.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q84254070 and verified on https://lefaham.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@lefaham.com', NULL, 'email', NULL, NULL),
('Lester-Thompson Fine Art', 'Professional services and software', 'SMB and Mid-market', 'United States', NULL, 'https://www.lesterthompsonfineart.com', 'https://www.lesterthompsonfineart.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.lesterthompsonfineart.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q130461703 and verified on https://www.lesterthompsonfineart.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@lesterthompsonfineart.com', NULL, 'email', NULL, NULL),
('librairie Vignes', 'Professional services and software', 'SMB and Mid-market', 'France', NULL, 'https://www.librairievignes.com', 'https://www.librairievignes.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.librairievignes.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q109927014 and verified on https://www.librairievignes.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@librairievignes.com', NULL, 'email', NULL, NULL),
('LTM Films', 'Professional services and software', 'SMB and Mid-market', 'France', NULL, 'http://www.ltmfilms.com', 'http://www.ltmfilms.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'http://www.ltmfilms.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q124566497 and verified on http://www.ltmfilms.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@ltmfilms.com', NULL, 'email', NULL, NULL),
('Maison Landemaine', 'Professional services and software', 'SMB and Mid-market', 'France', NULL, 'https://maisonlandemaine.com', 'https://maisonlandemaine.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://maisonlandemaine.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q89430707 and verified on https://maisonlandemaine.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@maisonlandemaine.com', NULL, 'email', NULL, NULL),
('Makansutra Gluttons Bay', 'Professional services and software', 'SMB and Mid-market', 'Singapore', NULL, 'https://makansutra.com', 'https://makansutra.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://makansutra.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q126899221 and verified on https://makansutra.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@makansutra.com', NULL, 'email', NULL, NULL),
('Morphogenesis', 'Professional services and software', 'SMB and Mid-market', 'Unknown', NULL, 'https://www.morphogenesis.org', 'https://www.morphogenesis.org/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.morphogenesis.org/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q25351835 and verified on https://www.morphogenesis.org/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@morphogenesis.org', NULL, 'email', NULL, NULL),
('Mother Production', 'Professional services and software', 'SMB and Mid-market', 'France', NULL, 'https://www.motherproduction.fr', 'https://www.motherproduction.fr/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.motherproduction.fr/contact', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q120870008 and verified on https://www.motherproduction.fr/contact.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@motherproduction.fr', NULL, 'email', NULL, NULL),
('NETexcom', 'Professional services and software', 'SMB and Mid-market', 'Monaco', NULL, 'https://www.netexcom.com', 'https://www.netexcom.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.netexcom.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q136164705 and verified on https://www.netexcom.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@netexcom.com', NULL, 'email', NULL, NULL),
('Paydens', 'Professional services and software', 'SMB and Mid-market', 'United Kingdom', NULL, 'https://www.paydens.com', 'https://www.paydens.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.paydens.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q122829194 and verified on https://www.paydens.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@paydens.com', NULL, 'email', NULL, NULL),
('Prolog Group', 'Professional services and software', 'SMB and Mid-market', 'Unknown', NULL, 'https://www.prolog-group.com', 'https://www.prolog-group.com/en/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.prolog-group.com/en/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q135660206 and verified on https://www.prolog-group.com/en/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@prolog-group.com', NULL, 'email', NULL, NULL),
('ProSiebenSat.1 PULS 4', 'Professional services and software', 'SMB and Mid-market', 'Austria', NULL, 'http://www.prosiebensat1puls4.com', 'http://www.prosiebensat1puls4.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'http://www.prosiebensat1puls4.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q66983251 and verified on http://www.prosiebensat1puls4.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@prosiebensat1puls4.com', NULL, 'email', NULL, NULL),
('RockBridge Productions', 'Professional services and software', 'SMB and Mid-market', 'Unknown', NULL, 'http://www.gorockbridge.com', 'http://www.gorockbridge.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'http://www.gorockbridge.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q124545014 and verified on http://www.gorockbridge.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@gorockbridge.com', NULL, 'email', NULL, NULL),
('VAPO', 'Professional services and software', 'SMB and Mid-market', 'New Zealand', NULL, 'https://www.vapo.co.nz', 'https://www.vapo.co.nz', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.vapo.co.nz', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q117236856 and verified on https://www.vapo.co.nz.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@vapo.co.nz', NULL, 'email', NULL, NULL),
('Videolabs', 'Professional services and software', 'SMB and Mid-market', 'France', NULL, 'https://videolabs.io', 'https://videolabs.io/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://videolabs.io/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q133822417 and verified on https://videolabs.io/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@videolabs.io', NULL, 'email', NULL, NULL),
('W1TTY', 'Professional services and software', 'SMB and Mid-market', 'United Kingdom', NULL, 'https://www.w1tty.com', 'https://www.w1tty.com', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.w1tty.com', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q132184722 and verified on https://www.w1tty.com.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'contact@w1tty.com', NULL, 'email', NULL, NULL),
('7info', 'Professional services and software', 'SMB and Mid-market', 'Russia', NULL, 'https://7info.ru', 'https://7info.ru', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://7info.ru', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q130504058 and verified on https://7info.ru.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@7info.ru', NULL, 'email', NULL, NULL),
('A1 Agency', 'Professional services and software', 'SMB and Mid-market', 'Unknown', NULL, 'http://www.a1agency.ch', 'http://www.a1agency.ch', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'http://www.a1agency.ch/contact', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q64596315 and verified on http://www.a1agency.ch/contact.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@a1agency.ch', NULL, 'email', NULL, NULL),
('Academixer', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://www.academixer.com', 'https://www.academixer.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.academixer.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q337282 and verified on https://www.academixer.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@academixer.com', NULL, 'email', NULL, NULL),
('Accent Hotels', 'Professional services and software', 'SMB and Mid-market', 'Hungary', NULL, 'https://accenthotels.com', 'https://accenthotels.com/hu', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://accenthotels.com/en/contact', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q136650539 and verified on https://accenthotels.com/en/contact.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@accenthotels.com', NULL, 'email', NULL, NULL),
('Adult Talent Managers LA', 'Professional services and software', 'SMB and Mid-market', 'United States', NULL, 'https://atmla.com', 'https://atmla.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://atmla.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q104149300 and verified on https://atmla.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@atmla.com', NULL, 'email', NULL, NULL),
('ae group', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://www.ae-group.de', 'https://www.ae-group.de/de/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.ae-group.de/de/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q83643841 and verified on https://www.ae-group.de/de/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@ae-group.de', NULL, 'email', NULL, NULL),
('Agenzia Giornalistica Italia', 'Professional services and software', 'SMB and Mid-market', 'Italy', NULL, 'https://www.agi.it', 'https://www.agi.it', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.agi.it', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q3606450 and verified on https://www.agi.it.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@agi.it', NULL, 'email', NULL, NULL),
('Air Alliance Express', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://air-alliance.de', 'https://air-alliance.de/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://air-alliance.de/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q15781907 and verified on https://air-alliance.de/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@air-alliance.de', NULL, 'email', NULL, NULL),
('Aksari Resort Ubud', 'Professional services and software', 'SMB and Mid-market', 'Indonesia', NULL, 'https://www.aksariubud.com', 'https://www.aksariubud.com', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.aksariubud.com', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q111137902 and verified on https://www.aksariubud.com.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@aksariubud.com', NULL, 'email', NULL, NULL),
('Alam Kulkul Boutique Resort', 'Professional services and software', 'SMB and Mid-market', 'Indonesia', NULL, 'http://alamkulkul.com', 'http://alamkulkul.com', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'http://alamkulkul.com', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q110775132 and verified on http://alamkulkul.com.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@alamkulkul.com', NULL, 'email', NULL, NULL),
('Alde Gott', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://www.aldegott.de', 'https://www.aldegott.de/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.aldegott.de/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q2640393 and verified on https://www.aldegott.de/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@aldegott.de', NULL, 'email', NULL, NULL),
('Altenauer Brauerei', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://altenauer-brauerei.de', 'https://altenauer-brauerei.de', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://altenauer-brauerei.de', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q52060253 and verified on https://altenauer-brauerei.de.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@altenauer-brauerei.de', NULL, 'email', NULL, NULL),
('Alter Ego Media', 'Professional services and software', 'SMB and Mid-market', 'Greece', NULL, 'https://www.alteregomedia.org', 'https://www.alteregomedia.org', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.alteregomedia.org', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q131675360 and verified on https://www.alteregomedia.org.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@alteregomedia.org', NULL, 'email', NULL, NULL),
('Amarea Resort Ubud', 'Professional services and software', 'SMB and Mid-market', 'Indonesia', NULL, 'https://www.amareaubud.com', 'https://www.amareaubud.com', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.amareaubud.com', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q117476125 and verified on https://www.amareaubud.com.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@amareaubud.com', NULL, 'email', NULL, NULL),
('Amasus Shipping', 'Professional services and software', 'SMB and Mid-market', 'Netherlands', NULL, 'https://www.amasus.nl', 'https://www.amasus.nl/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.amasus.nl/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q65179890 and verified on https://www.amasus.nl/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@amasus.nl', NULL, 'email', NULL, NULL),
('Ambreus', 'Professional services and software', 'SMB and Mid-market', 'Belgium', NULL, 'https://www.ambreus.be', 'https://www.ambreus.be/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.ambreus.be/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q135443250 and verified on https://www.ambreus.be/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@ambreus.be', NULL, 'email', NULL, NULL),
('Ambulanz Mobile', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://www.ambulanzmobile.de', 'https://www.ambulanzmobile.de/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.ambulanzmobile.de/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q67450516 and verified on https://www.ambulanzmobile.de/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@ambulanzmobile.de', NULL, 'email', NULL, NULL),
('Ameriabank', 'Professional services and software', 'SMB and Mid-market', 'Armenia', NULL, 'https://ameriabank.am', 'https://ameriabank.am', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://ameriabank.am/contact-us', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q4742492 and verified on https://ameriabank.am/contact-us.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@ameriabank.am', NULL, 'email', NULL, NULL),
('America’s Kids', 'Professional services and software', 'SMB and Mid-market', 'United States', NULL, 'https://www.americaskids.com', 'https://www.americaskids.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.americaskids.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q119141496 and verified on https://www.americaskids.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@americaskids.com', NULL, 'email', NULL, NULL),
('Angeln-Bahn', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'http://www.angelner-dampfeisenbahn.de', 'http://www.angelner-dampfeisenbahn.de/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'http://www.angelner-dampfeisenbahn.de/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q535314 and verified on http://www.angelner-dampfeisenbahn.de/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@angelner-dampfeisenbahn.de', NULL, 'email', NULL, NULL),
('Anthill Studios', 'Professional services and software', 'SMB and Mid-market', 'Nigeria', NULL, 'https://www.anthillstudios.com', 'https://www.anthillstudios.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.anthillstudios.com/contact', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q134431780 and verified on https://www.anthillstudios.com/contact.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@anthillstudios.com', NULL, 'email', NULL, NULL),
('Aqualand Köln', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://aqualand.de', 'https://aqualand.de', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://aqualand.de', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q119104192 and verified on https://aqualand.de.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@aqualand.de', NULL, 'email', NULL, NULL),
('AquaMagis Plettenberg', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://www.aquamagis.de', 'https://www.aquamagis.de', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.aquamagis.de/contact', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q82309236 and verified on https://www.aquamagis.de/contact.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@aquamagis.de', NULL, 'email', NULL, NULL),
('Arholma Nord', 'Professional services and software', 'SMB and Mid-market', 'Sweden', NULL, 'https://arholmanord.se', 'https://arholmanord.se/boende/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://arholmanord.se/boende/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q134676671 and verified on https://arholmanord.se/boende/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@arholmanord.se', NULL, 'email', NULL, NULL),
('Armenia Airways', 'Professional services and software', 'SMB and Mid-market', 'Armenia', NULL, 'https://armeniaairways.am', 'https://armeniaairways.am', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://armeniaairways.am', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q63441520 and verified on https://armeniaairways.am.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@armeniaairways.am', NULL, 'email', NULL, NULL),
('Art Bar', 'Professional services and software', 'SMB and Mid-market', 'United States', NULL, 'https://www.artbar.com', 'https://www.artbar.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.artbar.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q120679373 and verified on https://www.artbar.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@artbar.com', NULL, 'email', NULL, NULL),
('Astera Villa Canggu', 'Professional services and software', 'SMB and Mid-market', 'Indonesia', NULL, 'https://www.asteracanggu.com', 'https://www.asteracanggu.com', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.asteracanggu.com', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q117476360 and verified on https://www.asteracanggu.com.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@asteracanggu.com', NULL, 'email', NULL, NULL),
('AT-Prod', 'Professional services and software', 'SMB and Mid-market', 'Belgium', NULL, 'https://at-prod.com', 'https://at-prod.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://at-prod.com/contact', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q121792774 and verified on https://at-prod.com/contact.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@at-prod.com', NULL, 'email', NULL, NULL),
('Atomium', 'Professional services and software', 'SMB and Mid-market', 'Belgium', NULL, 'https://atomium.be', 'https://atomium.be/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://atomium.be/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q111632898 and verified on https://atomium.be/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@atomium.be', NULL, 'email', NULL, NULL),
('Aurora Productions', 'Professional services and software', 'SMB and Mid-market', 'United States', NULL, 'https://auroraprod.com', 'https://auroraprod.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://auroraprod.com/contact', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q125130302 and verified on https://auroraprod.com/contact.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@auroraprod.com', NULL, 'email', NULL, NULL),
('AutoLPGas', 'Professional services and software', 'SMB and Mid-market', 'Georgia', NULL, 'https://lpgauto.ge', 'https://lpgauto.ge', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://lpgauto.ge/contact', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q131470035 and verified on https://lpgauto.ge/contact.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@lpgauto.ge', NULL, 'email', NULL, NULL),
('AVU', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://www.avu.de', 'https://www.avu.de/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.avu.de/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q422118 and verified on https://www.avu.de/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@avu.de', NULL, 'email', NULL, NULL),
('Ayona Villa', 'Professional services and software', 'SMB and Mid-market', 'Indonesia', NULL, 'https://www.ayonavilla.com', 'https://www.ayonavilla.com', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.ayonavilla.com', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q110978490 and verified on https://www.ayonavilla.com.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@ayonavilla.com', NULL, 'email', NULL, NULL),
('Azúr Drug store', 'Professional services and software', 'SMB and Mid-market', 'Hungary', NULL, 'https://www.azur.hu', 'https://www.azur.hu/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.azur.hu/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q135415649 and verified on https://www.azur.hu/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@azur.hu', NULL, 'email', NULL, NULL),
('Badeparadies Schwarzwald', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://www.badeparadies-schwarzwald.de', 'https://www.badeparadies-schwarzwald.de', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.badeparadies-schwarzwald.de', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q23787483 and verified on https://www.badeparadies-schwarzwald.de.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@badeparadies-schwarzwald.de', NULL, 'email', NULL, NULL),
('Baka Stenugnsbageri', 'Professional services and software', 'SMB and Mid-market', 'Sweden', NULL, 'https://bakastenugnsbageri.se', 'https://bakastenugnsbageri.se/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://bakastenugnsbageri.se/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q113238541 and verified on https://bakastenugnsbageri.se/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@bakastenugnsbageri.se', NULL, 'email', NULL, NULL),
('Ballistol', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://ballistol.de', 'https://ballistol.de/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://ballistol.de/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q352266 and verified on https://ballistol.de/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@ballistol.de', NULL, 'email', NULL, NULL),
('Bankovní identita', 'Professional services and software', 'SMB and Mid-market', 'Czech Republic', NULL, 'https://www.bankid.cz', 'https://www.bankid.cz/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.bankid.cz/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q102263517 and verified on https://www.bankid.cz/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@bankid.cz', NULL, 'email', NULL, NULL),
('Bartholet Maschinenbau', 'Professional services and software', 'SMB and Mid-market', 'Switzerland', NULL, 'https://www.bartholet.swiss', 'https://www.bartholet.swiss/de', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.bartholet.swiss/de', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q88689002 and verified on https://www.bartholet.swiss/de.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@bartholet.swiss', NULL, 'email', NULL, NULL),
('Basilico', 'Professional services and software', 'SMB and Mid-market', 'Egypt', NULL, 'https://basilicoeg.com', 'https://basilicoeg.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://basilicoeg.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q112745202 and verified on https://basilicoeg.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@basilicoeg.com', NULL, 'email', NULL, NULL),
('BAU-SYSTEME 92', 'Professional services and software', 'SMB and Mid-market', 'Hungary', NULL, 'https://bau92.hu', 'https://bau92.hu/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://bau92.hu/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q136500206 and verified on https://bau92.hu/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@bau92.hu', NULL, 'email', NULL, NULL),
('Bavaria Studios & Production Services', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'http://www.bavaria-studios.de', 'http://www.bavaria-studios.de/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'http://www.bavaria-studios.de/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q811997 and verified on http://www.bavaria-studios.de/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@bavaria-studios.de', NULL, 'email', NULL, NULL),
('Bay’s - Asianfood & Sushi', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://www.bays-restaurant.de', 'https://www.bays-restaurant.de/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.bays-restaurant.de/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q96743244 and verified on https://www.bays-restaurant.de/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@bays-restaurant.de', NULL, 'email', NULL, NULL),
('Belgian Health Care Knowledge Centre', 'Professional services and software', 'SMB and Mid-market', 'Belgium', NULL, 'https://kce.fgov.be', 'https://kce.fgov.be/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://kce.fgov.be/contact-us', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q2107482 and verified on https://kce.fgov.be/contact-us.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@kce.fgov.be', NULL, 'email', NULL, NULL),
('Belgian National Orchestra', 'Professional services and software', 'SMB and Mid-market', 'Belgium', NULL, 'https://www.nationalorchestra.be', 'https://www.nationalorchestra.be/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.nationalorchestra.be/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q1910975 and verified on https://www.nationalorchestra.be/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@nationalorchestra.be', NULL, 'email', NULL, NULL),
('BeNEX', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://benex.de', 'https://benex.de/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://benex.de/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q473581 and verified on https://benex.de/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@benex.de', NULL, 'email', NULL, NULL),
('BentBox', 'Professional services and software', 'SMB and Mid-market', 'Kingdom of the Netherlands', NULL, 'https://bentbox.co', 'https://bentbox.co/cover', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://bentbox.co/cover', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q106504105 and verified on https://bentbox.co/cover.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@bentbox.co', NULL, 'email', NULL, NULL),
('BestFilm.eu', 'Professional services and software', 'SMB and Mid-market', 'Estonia', NULL, 'https://www.bestfilm.eu', 'https://www.bestfilm.eu/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.bestfilm.eu/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q124538408 and verified on https://www.bestfilm.eu/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@bestfilm.eu', NULL, 'email', NULL, NULL),
('Bildersturm Filmproduktion', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://www.bildersturm-film.de', 'https://www.bildersturm-film.de/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.bildersturm-film.de/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q123585842 and verified on https://www.bildersturm-film.de/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@bildersturm-film.de', NULL, 'email', NULL, NULL),
('Billion', 'Professional services and software', 'SMB and Mid-market', 'Georgia', NULL, 'https://bilioni.ge', 'https://bilioni.ge/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://bilioni.ge/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q131469969 and verified on https://bilioni.ge/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@bilioni.ge', NULL, 'email', NULL, NULL),
('Biotech Solution Company Limited', 'Professional services and software', 'SMB and Mid-market', 'Nigeria', NULL, 'https://www.biotechng.com', 'https://www.biotechng.com', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.biotechng.com', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q127689760 and verified on https://www.biotechng.com.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@biotechng.com', NULL, 'email', NULL, NULL),
('BIOVELA Group', 'Professional services and software', 'SMB and Mid-market', 'Lithuania', NULL, 'https://www.biovela.lt', 'https://www.biovela.lt/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.biovela.lt/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q15784956 and verified on https://www.biovela.lt/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@biovela.lt', NULL, 'email', NULL, NULL),
('Biržų duona', 'Professional services and software', 'SMB and Mid-market', 'Lithuania', NULL, 'https://www.birzuduona.lt', 'https://www.birzuduona.lt/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.birzuduona.lt/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q136814388 and verified on https://www.birzuduona.lt/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@birzuduona.lt', NULL, 'email', NULL, NULL),
('Black Angel', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://www.blackangel-halle.de', 'https://www.blackangel-halle.de', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.blackangel-halle.de', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q110243020 and verified on https://www.blackangel-halle.de.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@blackangel-halle.de', NULL, 'email', NULL, NULL),
('Blitch Knevel Architects', 'Professional services and software', 'SMB and Mid-market', 'United States', NULL, 'https://blitchknevel.com', 'https://blitchknevel.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://blitchknevel.com/contact-us', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q136449516 and verified on https://blitchknevel.com/contact-us.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@blitchknevel.com', NULL, 'email', NULL, NULL),
('Bluemont New Zealand', 'Professional services and software', 'SMB and Mid-market', 'New Zealand', NULL, 'https://www.bluemont.nz', 'https://www.bluemont.nz/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.bluemont.nz/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q135636094 and verified on https://www.bluemont.nz/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@bluemont.nz', NULL, 'email', NULL, NULL),
('Blueprint Media', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://www.bp-media.tv', 'https://www.bp-media.tv/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.bp-media.tv/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q121154895 and verified on https://www.bp-media.tv/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@bp-media.tv', NULL, 'email', NULL, NULL),
('Borough', 'Professional services and software', 'SMB and Mid-market', 'United States', NULL, 'https://www.boroughmpls.com', 'https://www.boroughmpls.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.boroughmpls.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q64390960 and verified on https://www.boroughmpls.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@boroughmpls.com', NULL, 'email', NULL, NULL),
('Bos Bros. Film & TV Productions', 'Professional services and software', 'SMB and Mid-market', 'Netherlands', NULL, 'http://www.bosbros.com', 'http://www.bosbros.com', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'http://www.bosbros.com', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q47465408 and verified on http://www.bosbros.com.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@bosbros.com', NULL, 'email', NULL, NULL),
('Brauerei Bosch', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'http://www.brauerei-bosch.de', 'http://www.brauerei-bosch.de/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'http://www.brauerei-bosch.de/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q900128 and verified on http://www.brauerei-bosch.de/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@brauerei-bosch.de', NULL, 'email', NULL, NULL),
('Brauerei Faust Miltenberg', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://faust.de', 'https://faust.de/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://faust.de/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q900176 and verified on https://faust.de/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@faust.de', NULL, 'email', NULL, NULL),
('BRAVE Management', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://bravemanagement.de', 'https://bravemanagement.de', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://bravemanagement.de', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q135440497 and verified on https://bravemanagement.de.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@bravemanagement.de', NULL, 'email', NULL, NULL),
('Brewery De Troch', 'Professional services and software', 'SMB and Mid-market', 'Belgium', NULL, 'https://www.detroch.be', 'https://www.detroch.be/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.detroch.be/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q2500112 and verified on https://www.detroch.be/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@detroch.be', NULL, 'email', NULL, NULL),
('Brewery Strubbe', 'Professional services and software', 'SMB and Mid-market', 'Belgium', NULL, 'https://www.brouwerij-strubbe.be', 'https://www.brouwerij-strubbe.be', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.brouwerij-strubbe.be', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q2732852 and verified on https://www.brouwerij-strubbe.be.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@brouwerij-strubbe.be', NULL, 'email', NULL, NULL),
('Brouwerij De Molen', 'Professional services and software', 'SMB and Mid-market', 'Netherlands', NULL, 'https://brouwerijdemolen.nl', 'https://brouwerijdemolen.nl/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://brouwerijdemolen.nl/contact', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q1828277 and verified on https://brouwerijdemolen.nl/contact.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@brouwerijdemolen.nl', NULL, 'email', NULL, NULL),
('Brouwerij Kestemont', 'Professional services and software', 'SMB and Mid-market', 'Belgium', NULL, 'https://www.brouwerijkestemont.be', 'https://www.brouwerijkestemont.be/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.brouwerijkestemont.be/contact', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q124623812 and verified on https://www.brouwerijkestemont.be/contact.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@brouwerijkestemont.be', NULL, 'email', NULL, NULL),
('Brune-Mettcker Druck- und Verlagsgesellschaft', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://brune-mettcker.de', 'https://brune-mettcker.de/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://brune-mettcker.de/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q62113857 and verified on https://brune-mettcker.de/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@brune-mettcker.de', NULL, 'email', NULL, NULL),
('Båtshaket', 'Professional services and software', 'SMB and Mid-market', 'Sweden', NULL, 'https://www.batshaket.se', 'https://www.batshaket.se/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.batshaket.se/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q134589221 and verified on https://www.batshaket.se/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@batshaket.se', NULL, 'email', NULL, NULL),
('Cafe & Restaurant Spreewehrmühle', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'http://www.spreewehrmuehle.de', 'http://www.spreewehrmuehle.de/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'http://www.spreewehrmuehle.de/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q98522088 and verified on http://www.spreewehrmuehle.de/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@spreewehrmuehle.de', NULL, 'email', NULL, NULL),
('Café Libertad Kollektiv', 'Professional services and software', 'SMB and Mid-market', 'Germany', NULL, 'https://www.cafe-libertad.de', 'https://www.cafe-libertad.de/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://www.cafe-libertad.de/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q74507072 and verified on https://www.cafe-libertad.de/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@cafe-libertad.de', NULL, 'email', NULL, NULL),
('CapeBio', 'Professional services and software', 'SMB and Mid-market', 'South Africa', NULL, 'https://capebiosa.com', 'https://capebiosa.com/', 'Official contact email verified on website', 'Public email appears on website page and matches domain.', 'https://capebiosa.com/', '2026-03-05', 66, 'AI adoption training for operations and business teams', 'Send first outreach email with quick diagnostic offer.', 'new', 'Source structured from Wikidata http://www.wikidata.org/entity/Q122500296 and verified on https://capebiosa.com/.', 66, 62, 58, 'warm', 'ready_to_contact', 'done', NULL, NULL, NULL, NULL, 'info@capebiosa.com', NULL, 'email', NULL, NULL)
ON CONFLICT (company_name, signal_source_url) DO UPDATE SET
  contact_email = EXCLUDED.contact_email,
  preferred_channel = EXCLUDED.preferred_channel,
  pipeline_stage = EXCLUDED.pipeline_stage,
  enrichment_status = EXCLUDED.enrichment_status,
  priority_score = GREATEST(public.market_leads.priority_score, EXCLUDED.priority_score),
  updated_at = NOW();
