export interface Lesson {
  id: string;
  title: string;
  duration: string;
  type: "video" | "lecture" | "exercise";
}

export interface Course {
  slug: string;
  title: string;
  subtitle: string;
  icon: string;
  level: "Débutant" | "Intermédiaire" | "Avancé";
  duration: string;
  lessonsCount: number;
  plan: "free" | "starter" | "team";
  category: string;
  tags: string[];
  description: string;
  outcomes: string[];
  lessons: Lesson[];
  color: string;
  bgColor: string;
}

export const COURSES: Course[] = [
  {
    slug: "ia-entreprise-guide-debutant",
    title: "L'IA en entreprise : Guide du débutant",
    subtitle: "Comprendre et démarrer votre transformation IA",
    icon: "🚀",
    level: "Débutant",
    duration: "1h30",
    lessonsCount: 6,
    plan: "free",
    category: "Fondamentaux",
    tags: ["IA", "Stratégie", "Business"],
    color: "text-indigo-600",
    bgColor: "bg-indigo-50 border-indigo-100",
    description: "Ce cours vous donne toutes les bases pour comprendre l'IA et identifier les opportunités d'automatisation dans votre entreprise. Pas besoin d'être technique — 100% orienté business.",
    outcomes: [
      "Comprendre les concepts clés de l'IA sans jargon technique",
      "Identifier les 5 zones d'automatisation à fort ROI dans votre business",
      "Construire votre feuille de route IA en 30 minutes",
      "Éviter les erreurs classiques des premières implémentations",
      "Convaincre votre direction et vos équipes",
    ],
    lessons: [
      { id: "1-1", title: "L'IA en 2025 : ce qui a vraiment changé", duration: "12 min", type: "lecture" },
      { id: "1-2", title: "Les 4 types d'automatisation IA", duration: "15 min", type: "lecture" },
      { id: "1-3", title: "Identifier vos quick wins (< 1 semaine)", duration: "18 min", type: "exercise" },
      { id: "1-4", title: "Les erreurs qui coûtent cher — et comment les éviter", duration: "14 min", type: "lecture" },
      { id: "1-5", title: "Construire votre roadmap IA", duration: "20 min", type: "exercise" },
      { id: "1-6", title: "Pitcher l'IA en interne (template inclus)", duration: "11 min", type: "exercise" },
    ],
  },
  {
    slug: "comprendre-ia-generative",
    title: "Comprendre l'IA générative",
    subtitle: "ChatGPT, Claude, Midjourney : ce que ça change concrètement",
    icon: "🧠",
    level: "Débutant",
    duration: "1h15",
    lessonsCount: 5,
    plan: "free",
    category: "Fondamentaux",
    tags: ["ChatGPT", "IA Générative", "LLM"],
    color: "text-purple-600",
    bgColor: "bg-purple-50 border-purple-100",
    description: "Démystifiez l'IA générative sans jargon. Comprenez ce que font réellement ChatGPT, Claude et les LLM, et surtout comment les exploiter dans votre activité quotidienne.",
    outcomes: [
      "Comprendre le fonctionnement des LLM en termes simples",
      "Savoir quand utiliser l'IA générative (et quand ne pas)",
      "Écrire des prompts efficaces pour des résultats pro",
      "Comparer les outils du marché objectivement",
      "Identifier 10 cas d'usage immédiatement applicables",
    ],
    lessons: [
      { id: "7-1", title: "Comment fonctionne un LLM (sans maths)", duration: "14 min", type: "lecture" },
      { id: "7-2", title: "ChatGPT vs Claude vs Gemini : le vrai comparatif", duration: "16 min", type: "lecture" },
      { id: "7-3", title: "L'art du prompt : obtenir des résultats pro", duration: "20 min", type: "exercise" },
      { id: "7-4", title: "10 cas d'usage concrets par métier", duration: "15 min", type: "lecture" },
      { id: "7-5", title: "Les limites à connaître absolument", duration: "10 min", type: "lecture" },
    ],
  },
  {
    slug: "vocabulaire-ia-essentiel",
    title: "Le vocabulaire IA essentiel",
    subtitle: "Parlez IA couramment en 1 heure",
    icon: "📖",
    level: "Débutant",
    duration: "1h",
    lessonsCount: 5,
    plan: "free",
    category: "Fondamentaux",
    tags: ["Glossaire", "Bases", "Culture IA"],
    color: "text-teal-600",
    bgColor: "bg-teal-50 border-teal-100",
    description: "API, LLM, RAG, fine-tuning, prompt engineering... Comprenez enfin tous les termes IA qui circulent dans vos réunions. Glossaire interactif + quiz.",
    outcomes: [
      "Maîtriser les 50 termes IA incontournables",
      "Distinguer marketing et réalité technique",
      "Participer aux discussions IA en confiance",
      "Évaluer les solutions vendues par les prestataires",
      "Passer le quiz de certification vocabulaire",
    ],
    lessons: [
      { id: "8-1", title: "Les bases : ML, DL, NLP, LLM", duration: "12 min", type: "lecture" },
      { id: "8-2", title: "Les termes techniques démystifiés", duration: "14 min", type: "lecture" },
      { id: "8-3", title: "Le jargon business de l'IA", duration: "12 min", type: "lecture" },
      { id: "8-4", title: "Décrypter les pitchs des vendeurs d'IA", duration: "12 min", type: "exercise" },
      { id: "8-5", title: "Quiz final : parlez-vous IA ?", duration: "10 min", type: "exercise" },
    ],
  },
  {
    slug: "choisir-outils-ia",
    title: "Choisir les bons outils IA pour son business",
    subtitle: "Arrêtez de payer pour des outils que vous n'utilisez pas",
    icon: "🔧",
    level: "Débutant",
    duration: "1h30",
    lessonsCount: 6,
    plan: "starter",
    category: "Fondamentaux",
    tags: ["Outils", "Comparatif", "Budget"],
    color: "text-slate-600",
    bgColor: "bg-slate-50 border-slate-100",
    description: "Avec +500 outils IA sur le marché, comment choisir les bons ? Matrice de décision, comparatifs honnêtes et checklist pour ne pas se tromper.",
    outcomes: [
      "Utiliser la matrice de sélection d'outils IA",
      "Comparer objectivement les solutions du marché",
      "Éviter le piège de l'outil shiny syndrome",
      "Construire votre stack IA cohérent",
      "Négocier vos licences intelligemment",
    ],
    lessons: [
      { id: "9-1", title: "La jungle des outils IA : s'y retrouver", duration: "12 min", type: "lecture" },
      { id: "9-2", title: "Matrice de décision : besoin vs solution", duration: "18 min", type: "exercise" },
      { id: "9-3", title: "Les 10 outils incontournables par fonction", duration: "16 min", type: "lecture" },
      { id: "9-4", title: "Construire son stack IA cohérent", duration: "14 min", type: "exercise" },
      { id: "9-5", title: "Budget IA : combien investir ?", duration: "12 min", type: "lecture" },
      { id: "9-6", title: "Checklist avant de souscrire", duration: "18 min", type: "exercise" },
    ],
  },
  {
    slug: "ia-ethique-rgpd",
    title: "IA éthique et conformité RGPD",
    subtitle: "Utilisez l'IA sans risque juridique",
    icon: "⚖️",
    level: "Intermédiaire",
    duration: "1h45",
    lessonsCount: 6,
    plan: "starter",
    category: "Fondamentaux",
    tags: ["RGPD", "Éthique", "Juridique", "Conformité"],
    color: "text-cyan-600",
    bgColor: "bg-cyan-50 border-cyan-100",
    description: "L'IA c'est puissant, mais les risques juridiques sont réels. Ce cours couvre le RGPD appliqué à l'IA, les biais algorithmiques et la conformité européenne (AI Act).",
    outcomes: [
      "Appliquer le RGPD à vos projets IA",
      "Identifier et mitiger les biais algorithmiques",
      "Comprendre l'AI Act européen et ses implications",
      "Rédiger une charte IA pour votre entreprise",
      "Documenter vos usages IA pour les audits",
    ],
    lessons: [
      { id: "10-1", title: "RGPD et IA : ce que dit vraiment la loi", duration: "16 min", type: "lecture" },
      { id: "10-2", title: "L'AI Act européen : ce qui change", duration: "18 min", type: "lecture" },
      { id: "10-3", title: "Identifier les biais dans vos données", duration: "20 min", type: "exercise" },
      { id: "10-4", title: "Data privacy by design", duration: "16 min", type: "lecture" },
      { id: "10-5", title: "Rédiger votre charte IA interne", duration: "22 min", type: "exercise" },
      { id: "10-6", title: "Checklist conformité avant mise en prod", duration: "13 min", type: "exercise" },
    ],
  },
  {
    slug: "securite-donnees-ia",
    title: "Sécurité des données et IA",
    subtitle: "Protégez vos données quand vous utilisez l'IA",
    icon: "🔒",
    level: "Intermédiaire",
    duration: "1h30",
    lessonsCount: 6,
    plan: "starter",
    category: "Fondamentaux",
    tags: ["Sécurité", "Données", "Confidentialité"],
    color: "text-rose-600",
    bgColor: "bg-rose-50 border-rose-100",
    description: "Vos données passent par des API, des LLM, des services cloud. Apprenez à sécuriser chaque maillon de la chaîne pour dormir tranquille.",
    outcomes: [
      "Auditer les flux de données de vos outils IA",
      "Configurer les garde-fous de confidentialité",
      "Choisir entre API privée, on-premise ou cloud",
      "Former vos équipes aux bonnes pratiques de sécurité IA",
      "Créer votre policy de sécurité IA",
    ],
    lessons: [
      { id: "11-1", title: "Où vont vos données quand vous utilisez l'IA ?", duration: "14 min", type: "lecture" },
      { id: "11-2", title: "Les risques réels (avec exemples)", duration: "12 min", type: "lecture" },
      { id: "11-3", title: "Configurer la confidentialité dans OpsAI", duration: "18 min", type: "video" },
      { id: "11-4", title: "Cloud vs on-premise : matrice de décision", duration: "16 min", type: "exercise" },
      { id: "11-5", title: "Former vos équipes (kit prêt à l'emploi)", duration: "15 min", type: "exercise" },
      { id: "11-6", title: "Votre policy de sécurité IA en 30 min", duration: "15 min", type: "exercise" },
    ],
  },
  {
    slug: "conduite-changement-ia",
    title: "Conduite du changement IA",
    subtitle: "Faites adopter l'IA par vos équipes (sans résistance)",
    icon: "🤝",
    level: "Avancé",
    duration: "2h",
    lessonsCount: 7,
    plan: "team",
    category: "Fondamentaux",
    tags: ["Management", "Adoption", "Change Management"],
    color: "text-violet-600",
    bgColor: "bg-violet-50 border-violet-100",
    description: "L'IA ne sert à rien si personne ne l'utilise. Ce cours vous donne le playbook complet pour accompagner vos équipes : communication, formation, quick wins et gestion des résistances.",
    outcomes: [
      "Identifier les profils résistants et adaptateurs",
      "Construire un plan de communication IA efficace",
      "Créer des ambassadeurs IA dans chaque équipe",
      "Mesurer l'adoption avec les bons indicateurs",
      "Gérer les peurs et objections concrètement",
    ],
    lessons: [
      { id: "12-1", title: "Pourquoi 70% des projets IA échouent à l'adoption", duration: "14 min", type: "lecture" },
      { id: "12-2", title: "Les 4 profils face au changement", duration: "16 min", type: "lecture" },
      { id: "12-3", title: "Votre plan de communication IA", duration: "20 min", type: "exercise" },
      { id: "12-4", title: "Former les early adopters (programme)", duration: "18 min", type: "exercise" },
      { id: "12-5", title: "Gérer les résistances (scripts et techniques)", duration: "18 min", type: "lecture" },
      { id: "12-6", title: "Mesurer l'adoption réelle", duration: "12 min", type: "exercise" },
      { id: "12-7", title: "De l'adoption au réflexe : ancrer les habitudes", duration: "12 min", type: "lecture" },
    ],
  },
  {
    slug: "automatiser-emails-ia",
    title: "Automatiser ses emails avec l'IA",
    subtitle: "Récupérez 2h par jour sur votre boîte mail",
    icon: "📧",
    level: "Débutant",
    duration: "1h45",
    lessonsCount: 7,
    plan: "free",
    category: "Automatisation",
    tags: ["Gmail", "Outlook", "Emails", "Productivité"],
    color: "text-red-600",
    bgColor: "bg-red-50 border-red-100",
    description: "Votre boîte mail vous dévore ? Ce cours vous apprend à classifier, prioriser et répondre automatiquement à vos emails grâce à l'IA. Compatible Gmail et Outlook.",
    outcomes: [
      "Mettre en place un triage automatique par priorité",
      "Créer des réponses types intelligentes pour 80% de vos emails",
      "Déléguer les emails de support à un agent IA",
      "Réduire le volume d'emails traités manuellement de 70%",
      "Configurer votre workflow email_triage dans OpsAI",
    ],
    lessons: [
      { id: "2-1", title: "Anatomie d'une boîte mail efficace", duration: "10 min", type: "lecture" },
      { id: "2-2", title: "Comment l'IA lit et comprend vos emails", duration: "14 min", type: "lecture" },
      { id: "2-3", title: "Configurer le triage IA (Gmail)", duration: "20 min", type: "video" },
      { id: "2-4", title: "Configurer le triage IA (Outlook)", duration: "18 min", type: "video" },
      { id: "2-5", title: "Créer vos templates de réponse IA", duration: "22 min", type: "exercise" },
      { id: "2-6", title: "Gérer les cas complexes et escalades", duration: "12 min", type: "lecture" },
      { id: "2-7", title: "Mesurer votre gain de temps", duration: "9 min", type: "exercise" },
    ],
  },
  {
    slug: "premier-workflow-ia",
    title: "Créer son premier workflow IA",
    subtitle: "De zéro à votre première automatisation en 45 min",
    icon: "⚡",
    level: "Débutant",
    duration: "2h",
    lessonsCount: 8,
    plan: "starter",
    category: "Automatisation",
    tags: ["Workflows", "OpsAI", "No-code"],
    color: "text-amber-600",
    bgColor: "bg-amber-50 border-amber-100",
    description: "Formation pratique pas à pas pour créer votre première automatisation IA avec OpsAI. À la fin du cours, vous avez un workflow en production qui tourne tout seul.",
    outcomes: [
      "Maîtriser l'interface OpsAI en moins d'une heure",
      "Choisir le bon template selon votre besoin",
      "Configurer, tester et déployer un workflow complet",
      "Connecter vos outils existants (Gmail, Slack, Notion...)",
      "Lire et interpréter les logs d'exécution",
    ],
    lessons: [
      { id: "3-1", title: "Tour d'horizon de l'interface OpsAI", duration: "10 min", type: "video" },
      { id: "3-2", title: "Choisir son premier template", duration: "12 min", type: "lecture" },
      { id: "3-3", title: "Connecter ses outils (intégrations)", duration: "20 min", type: "video" },
      { id: "3-4", title: "Configurer le workflow étape par étape", duration: "25 min", type: "exercise" },
      { id: "3-5", title: "Tester en conditions réelles", duration: "15 min", type: "exercise" },
      { id: "3-6", title: "Mettre en production et activer", duration: "10 min", type: "video" },
      { id: "3-7", title: "Surveiller et optimiser", duration: "14 min", type: "lecture" },
      { id: "3-8", title: "Passer au workflow suivant", duration: "14 min", type: "exercise" },
    ],
  },
  {
    slug: "automatiser-facturation",
    title: "Automatiser sa facturation avec l'IA",
    subtitle: "Factures envoyées, relances faites — sans lever le petit doigt",
    icon: "🧾",
    level: "Débutant",
    duration: "1h30",
    lessonsCount: 6,
    plan: "starter",
    category: "Automatisation",
    tags: ["Facturation", "Finance", "Stripe", "Relances"],
    color: "text-emerald-600",
    bgColor: "bg-emerald-50 border-emerald-100",
    description: "Automatisez la création, l'envoi et le suivi de vos factures. Relances intelligentes incluses. Compatible Stripe, QuickBooks et Pennylane.",
    outcomes: [
      "Générer des factures automatiquement après chaque vente",
      "Configurer les relances intelligentes (timing + ton)",
      "Synchroniser facturation et CRM",
      "Réduire les impayés de 40%",
      "Suivre votre trésorerie en temps réel",
    ],
    lessons: [
      { id: "13-1", title: "Le cycle de facturation idéal", duration: "10 min", type: "lecture" },
      { id: "13-2", title: "Connecter votre outil de facturation", duration: "18 min", type: "video" },
      { id: "13-3", title: "Workflow : facture auto après vente", duration: "22 min", type: "exercise" },
      { id: "13-4", title: "Relances intelligentes : timing et personnalisation", duration: "18 min", type: "exercise" },
      { id: "13-5", title: "Tableau de bord trésorerie", duration: "14 min", type: "video" },
      { id: "13-6", title: "Gérer les cas spéciaux (avoirs, litiges)", duration: "8 min", type: "lecture" },
    ],
  },
  {
    slug: "automatiser-onboarding-clients",
    title: "Automatiser l'onboarding client",
    subtitle: "Chaque nouveau client parfaitement accueilli, sans effort",
    icon: "🎉",
    level: "Intermédiaire",
    duration: "2h",
    lessonsCount: 7,
    plan: "starter",
    category: "Automatisation",
    tags: ["Onboarding", "Clients", "Satisfaction", "Rétention"],
    color: "text-pink-600",
    bgColor: "bg-pink-50 border-pink-100",
    description: "Un bon onboarding = un client fidèle. Créez une séquence d'accueil automatisée qui impressionne vos clients et réduit le churn dès J1.",
    outcomes: [
      "Concevoir une séquence d'onboarding en 5 étapes",
      "Personnaliser chaque email de bienvenue avec l'IA",
      "Automatiser la collecte des informations client",
      "Déclencher des alertes si un client est bloqué",
      "Mesurer votre score d'onboarding",
    ],
    lessons: [
      { id: "14-1", title: "Les 7 premiers jours : make or break", duration: "12 min", type: "lecture" },
      { id: "14-2", title: "Concevoir votre séquence d'accueil", duration: "18 min", type: "exercise" },
      { id: "14-3", title: "Emails de bienvenue personnalisés par l'IA", duration: "20 min", type: "exercise" },
      { id: "14-4", title: "Formulaires et collecte automatique", duration: "16 min", type: "video" },
      { id: "14-5", title: "Détecter les clients en difficulté", duration: "14 min", type: "lecture" },
      { id: "14-6", title: "Workflow complet : démo pas à pas", duration: "22 min", type: "video" },
      { id: "14-7", title: "KPIs d'onboarding à suivre", duration: "8 min", type: "exercise" },
    ],
  },
  {
    slug: "automatiser-support-client",
    title: "Automatiser le support client avec l'IA",
    subtitle: "Répondez en 30 secondes au lieu de 30 minutes",
    icon: "💬",
    level: "Intermédiaire",
    duration: "2h15",
    lessonsCount: 8,
    plan: "starter",
    category: "Automatisation",
    tags: ["Support", "Chatbot", "Zendesk", "Intercom"],
    color: "text-sky-600",
    bgColor: "bg-sky-50 border-sky-100",
    description: "Créez un support client IA qui résout 70% des tickets sans intervention humaine. Compatible Zendesk, Intercom et Crisp.",
    outcomes: [
      "Construire une base de connaissances IA-ready",
      "Configurer un chatbot qui résout vraiment les problèmes",
      "Mettre en place l'escalade intelligente",
      "Réduire le temps de réponse de 80%",
      "Analyser la satisfaction client automatiquement",
    ],
    lessons: [
      { id: "15-1", title: "L'état de l'art du support IA en 2025", duration: "12 min", type: "lecture" },
      { id: "15-2", title: "Construire votre base de connaissances", duration: "22 min", type: "exercise" },
      { id: "15-3", title: "Configurer le chatbot IA (step by step)", duration: "25 min", type: "video" },
      { id: "15-4", title: "Classification automatique des tickets", duration: "16 min", type: "exercise" },
      { id: "15-5", title: "Escalade intelligente : quand passer à l'humain", duration: "14 min", type: "lecture" },
      { id: "15-6", title: "Réponses suggérées pour les agents", duration: "18 min", type: "exercise" },
      { id: "15-7", title: "Analyse de satisfaction automatique", duration: "12 min", type: "video" },
      { id: "15-8", title: "Optimiser en continu avec les feedbacks", duration: "10 min", type: "lecture" },
    ],
  },
  {
    slug: "workflows-avances-conditions",
    title: "Workflows avancés : conditions et branchements",
    subtitle: "Créez des automatisations qui pensent comme vous",
    icon: "🔀",
    level: "Intermédiaire",
    duration: "2h30",
    lessonsCount: 8,
    plan: "team",
    category: "Automatisation",
    tags: ["Workflows", "Logique", "Avancé", "Conditions"],
    color: "text-fuchsia-600",
    bgColor: "bg-fuchsia-50 border-fuchsia-100",
    description: "Allez au-delà des workflows linéaires. Apprenez les conditions, branchements, boucles et gestion d'erreurs pour des automatisations professionnelles.",
    outcomes: [
      "Maîtriser les conditions if/else dans OpsAI",
      "Créer des workflows multi-branches complexes",
      "Gérer les erreurs et retries automatiquement",
      "Combiner plusieurs workflows en cascade",
      "Déboguer efficacement les workflows bloqués",
    ],
    lessons: [
      { id: "16-1", title: "Au-delà du workflow linéaire", duration: "12 min", type: "lecture" },
      { id: "16-2", title: "Conditions et branchements (if/else)", duration: "22 min", type: "video" },
      { id: "16-3", title: "Boucles et itérations", duration: "20 min", type: "exercise" },
      { id: "16-4", title: "Gestion d'erreurs et retries", duration: "18 min", type: "video" },
      { id: "16-5", title: "Variables et données entre les étapes", duration: "22 min", type: "exercise" },
      { id: "16-6", title: "Combiner plusieurs workflows", duration: "16 min", type: "exercise" },
      { id: "16-7", title: "Débogage avancé avec les logs", duration: "14 min", type: "video" },
      { id: "16-8", title: "Exercice : workflow multi-branches complet", duration: "26 min", type: "exercise" },
    ],
  },
  {
    slug: "automatiser-rh-recrutement",
    title: "Automatiser le recrutement et les RH",
    subtitle: "Du sourcing au contrat, l'IA gère le processus",
    icon: "👥",
    level: "Intermédiaire",
    duration: "2h15",
    lessonsCount: 8,
    plan: "team",
    category: "Automatisation",
    tags: ["RH", "Recrutement", "Onboarding", "Talents"],
    color: "text-lime-600",
    bgColor: "bg-lime-50 border-lime-100",
    description: "Automatisez le tri des CV, les pré-qualifications, la planification des entretiens et l'onboarding RH. Gagnez du temps sur les tâches à faible valeur ajoutée.",
    outcomes: [
      "Trier et scorer les CV automatiquement",
      "Pré-qualifier les candidats avec un chatbot",
      "Automatiser la prise de rendez-vous entretien",
      "Créer un processus d'onboarding RH automatisé",
      "Générer les contrats et documents RH par IA",
    ],
    lessons: [
      { id: "17-1", title: "Le recrutement IA-augmenté", duration: "14 min", type: "lecture" },
      { id: "17-2", title: "Tri automatique des CV (sans biais)", duration: "20 min", type: "video" },
      { id: "17-3", title: "Chatbot de pré-qualification candidat", duration: "22 min", type: "exercise" },
      { id: "17-4", title: "Planification auto des entretiens", duration: "16 min", type: "video" },
      { id: "17-5", title: "Scoring et matching candidat/poste", duration: "18 min", type: "exercise" },
      { id: "17-6", title: "Onboarding collaborateur automatisé", duration: "20 min", type: "exercise" },
      { id: "17-7", title: "Génération de documents RH", duration: "12 min", type: "video" },
      { id: "17-8", title: "Le processus complet de bout en bout", duration: "13 min", type: "lecture" },
    ],
  },
  {
    slug: "automatiser-comptabilite",
    title: "Automatiser sa comptabilité avec l'IA",
    subtitle: "Saisie, rapprochement et reporting en pilote automatique",
    icon: "🧮",
    level: "Intermédiaire",
    duration: "2h",
    lessonsCount: 7,
    plan: "team",
    category: "Automatisation",
    tags: ["Comptabilité", "Finance", "OCR", "Pennylane"],
    color: "text-yellow-600",
    bgColor: "bg-yellow-50 border-yellow-100",
    description: "L'IA lit vos factures, les classe, les saisit et fait le rapprochement bancaire. Vous n'avez plus qu'à valider. Compatible Pennylane, QuickBooks.",
    outcomes: [
      "Extraire automatiquement les données des factures (OCR IA)",
      "Classifier les dépenses par catégorie",
      "Automatiser le rapprochement bancaire",
      "Générer les écritures comptables",
      "Alerter sur les anomalies et doublons",
    ],
    lessons: [
      { id: "18-1", title: "L'IA en comptabilité : état des lieux", duration: "12 min", type: "lecture" },
      { id: "18-2", title: "OCR IA : extraire les données de factures", duration: "20 min", type: "video" },
      { id: "18-3", title: "Classification automatique des dépenses", duration: "18 min", type: "exercise" },
      { id: "18-4", title: "Rapprochement bancaire automatisé", duration: "22 min", type: "video" },
      { id: "18-5", title: "Génération des écritures comptables", duration: "16 min", type: "exercise" },
      { id: "18-6", title: "Détection d'anomalies et alertes", duration: "14 min", type: "lecture" },
      { id: "18-7", title: "Intégration avec votre expert-comptable", duration: "18 min", type: "exercise" },
    ],
  },
  {
    slug: "automatiser-marketing-contenu",
    title: "Automatiser le marketing de contenu",
    subtitle: "Publiez du contenu de qualité 5x plus vite",
    icon: "✍️",
    level: "Intermédiaire",
    duration: "2h30",
    lessonsCount: 9,
    plan: "team",
    category: "Automatisation",
    tags: ["Marketing", "Contenu", "SEO", "Réseaux sociaux"],
    color: "text-orange-600",
    bgColor: "bg-orange-50 border-orange-100",
    description: "De l'idéation à la publication, automatisez votre chaîne de contenu : articles, posts LinkedIn, newsletters, avec une qualité qui ne se voit pas.",
    outcomes: [
      "Générer des idées de contenu basées sur les tendances",
      "Rédiger des premiers jets IA de qualité",
      "Optimiser le SEO automatiquement",
      "Planifier et publier en multi-canal",
      "Recycler un contenu en 10 formats différents",
    ],
    lessons: [
      { id: "19-1", title: "La content factory IA : vue d'ensemble", duration: "14 min", type: "lecture" },
      { id: "19-2", title: "Veille et idéation de contenu par IA", duration: "16 min", type: "exercise" },
      { id: "19-3", title: "Rédiger des articles avec l'IA (sans être générique)", duration: "22 min", type: "exercise" },
      { id: "19-4", title: "Optimisation SEO automatique", duration: "18 min", type: "video" },
      { id: "19-5", title: "Posts LinkedIn et réseaux sociaux", duration: "16 min", type: "exercise" },
      { id: "19-6", title: "Newsletters automatisées", duration: "14 min", type: "video" },
      { id: "19-7", title: "Le recyclage de contenu (1 → 10 formats)", duration: "18 min", type: "exercise" },
      { id: "19-8", title: "Planification et publication multi-canal", duration: "14 min", type: "video" },
      { id: "19-9", title: "Mesurer la performance de votre contenu IA", duration: "18 min", type: "exercise" },
    ],
  },
  {
    slug: "automatiser-gestion-projets",
    title: "Automatiser la gestion de projets",
    subtitle: "Votre PM virtuel qui ne dort jamais",
    icon: "📋",
    level: "Intermédiaire",
    duration: "2h",
    lessonsCount: 7,
    plan: "team",
    category: "Automatisation",
    tags: ["Projets", "Notion", "Asana", "Productivité"],
    color: "text-indigo-600",
    bgColor: "bg-indigo-50 border-indigo-100",
    description: "Stand-ups résumés, tâches assignées, deadlines relancées, rapports d'avancement générés — automatisez le suivi projet avec l'IA.",
    outcomes: [
      "Automatiser les comptes-rendus de stand-up",
      "Assigner les tâches intelligemment par compétence",
      "Relancer automatiquement les deadlines en retard",
      "Générer des rapports d'avancement hebdomadaires",
      "Détecter les projets à risque en avance",
    ],
    lessons: [
      { id: "20-1", title: "Le PM augmenté par l'IA", duration: "12 min", type: "lecture" },
      { id: "20-2", title: "Résumés automatiques de réunions", duration: "18 min", type: "video" },
      { id: "20-3", title: "Attribution intelligente des tâches", duration: "20 min", type: "exercise" },
      { id: "20-4", title: "Relances et suivi de deadlines", duration: "16 min", type: "exercise" },
      { id: "20-5", title: "Rapports d'avancement auto", duration: "18 min", type: "video" },
      { id: "20-6", title: "Détection précoce des risques", duration: "14 min", type: "lecture" },
      { id: "20-7", title: "Intégrations Notion / Asana / Monday", duration: "22 min", type: "video" },
    ],
  },
  {
    slug: "orchestrer-workflows-complexes",
    title: "Orchestrer des workflows multi-équipes",
    subtitle: "Quand vos automatisations travaillent ensemble",
    icon: "🎼",
    level: "Avancé",
    duration: "2h45",
    lessonsCount: 9,
    plan: "team",
    category: "Automatisation",
    tags: ["Orchestration", "Architecture", "Scalabilité"],
    color: "text-red-600",
    bgColor: "bg-red-50 border-red-100",
    description: "Vous avez 10+ workflows qui tournent. Il est temps de les orchestrer en un système cohérent. Architecture, dépendances, monitoring et scaling.",
    outcomes: [
      "Cartographier vos workflows et leurs dépendances",
      "Architecturer un système d'automatisation scalable",
      "Gérer les files d'attente et la priorisation",
      "Monitorer l'ensemble depuis un dashboard unique",
      "Planifier l'évolution à 6-12 mois",
    ],
    lessons: [
      { id: "21-1", title: "Du workflow isolé au système intégré", duration: "14 min", type: "lecture" },
      { id: "21-2", title: "Cartographier vos automatisations", duration: "18 min", type: "exercise" },
      { id: "21-3", title: "Architecture événementielle (triggers/actions)", duration: "22 min", type: "lecture" },
      { id: "21-4", title: "Gestion des dépendances entre workflows", duration: "18 min", type: "exercise" },
      { id: "21-5", title: "Files d'attente et priorisation", duration: "16 min", type: "video" },
      { id: "21-6", title: "Dashboard de monitoring centralisé", duration: "20 min", type: "video" },
      { id: "21-7", title: "Gestion des pannes et failover", duration: "18 min", type: "exercise" },
      { id: "21-8", title: "Performance et optimisation", duration: "16 min", type: "lecture" },
      { id: "21-9", title: "Roadmap d'évolution 6-12 mois", duration: "13 min", type: "exercise" },
    ],
  },
  {
    slug: "ia-crm-ventes",
    title: "Intégrer l'IA dans son CRM et ses ventes",
    subtitle: "Boostez votre pipeline avec des leads qualifiés par IA",
    icon: "🎯",
    level: "Intermédiaire",
    duration: "2h30",
    lessonsCount: 9,
    plan: "team",
    category: "Ventes & CRM",
    tags: ["HubSpot", "Salesforce", "Leads", "IA"],
    color: "text-orange-600",
    bgColor: "bg-orange-50 border-orange-100",
    description: "Apprenez à utiliser l'IA pour qualifier vos leads, personnaliser vos relances et mettre à jour votre CRM automatiquement. Compatible HubSpot et Salesforce.",
    outcomes: [
      "Scorer vos leads automatiquement avec l'IA",
      "Personnaliser chaque séquence de vente à grande échelle",
      "Réduire le temps de saisie CRM de 80%",
      "Détecter les opportunités chaudes en temps réel",
      "Former votre équipe commerciale à travailler avec l'IA",
    ],
    lessons: [
      { id: "4-1", title: "Les données CRM comme carburant de l'IA", duration: "15 min", type: "lecture" },
      { id: "4-2", title: "Qualifier automatiquement les leads entrants", duration: "20 min", type: "video" },
      { id: "4-3", title: "Rédiger des emails de vente avec l'IA", duration: "18 min", type: "exercise" },
      { id: "4-4", title: "Mise à jour automatique des deals HubSpot", duration: "22 min", type: "video" },
      { id: "4-5", title: "Scorer et prioriser votre pipeline", duration: "20 min", type: "exercise" },
      { id: "4-6", title: "Détection des signaux d'achat", duration: "15 min", type: "lecture" },
      { id: "4-7", title: "Reporting commercial IA-powered", duration: "18 min", type: "exercise" },
      { id: "4-8", title: "Gérer les objections avec l'aide de l'IA", duration: "16 min", type: "lecture" },
      { id: "4-9", title: "Déploiement et formation de votre équipe", duration: "16 min", type: "exercise" },
    ],
  },
  {
    slug: "prospection-ia-linkedin",
    title: "Prospection IA sur LinkedIn",
    subtitle: "Générez des leads qualifiés pendant que vous dormez",
    icon: "🔍",
    level: "Débutant",
    duration: "1h45",
    lessonsCount: 7,
    plan: "starter",
    category: "Ventes & CRM",
    tags: ["LinkedIn", "Prospection", "Social Selling"],
    color: "text-blue-600",
    bgColor: "bg-blue-50 border-blue-100",
    description: "Identifiez, qualifiez et contactez vos prospects LinkedIn avec l'IA. Messages personnalisés à l'échelle, sans spam, avec un taux de réponse 3x supérieur.",
    outcomes: [
      "Identifier vos ICP sur LinkedIn avec l'IA",
      "Rédiger des messages d'accroche personnalisés",
      "Automatiser les séquences de suivi",
      "Analyser les profils et signaux d'intérêt",
      "Mesurer et optimiser votre taux de conversion",
    ],
    lessons: [
      { id: "22-1", title: "Le social selling IA : les nouvelles règles", duration: "12 min", type: "lecture" },
      { id: "22-2", title: "Définir votre ICP et le chercher par IA", duration: "18 min", type: "exercise" },
      { id: "22-3", title: "Analyser un profil en 10 secondes", duration: "14 min", type: "video" },
      { id: "22-4", title: "Rédiger des messages qui convertissent", duration: "22 min", type: "exercise" },
      { id: "22-5", title: "Séquences de suivi automatisées", duration: "16 min", type: "exercise" },
      { id: "22-6", title: "Ne pas se faire bloquer (bonnes pratiques)", duration: "10 min", type: "lecture" },
      { id: "22-7", title: "Dashboard de suivi prospection", duration: "13 min", type: "video" },
    ],
  },
  {
    slug: "chatbot-commercial-ia",
    title: "Créer un chatbot commercial IA",
    subtitle: "Un vendeur disponible 24h/24 sur votre site",
    icon: "🤖",
    level: "Intermédiaire",
    duration: "2h",
    lessonsCount: 7,
    plan: "starter",
    category: "Ventes & CRM",
    tags: ["Chatbot", "Ventes", "Conversion", "Website"],
    color: "text-violet-600",
    bgColor: "bg-violet-50 border-violet-100",
    description: "Construisez un chatbot commercial qui qualifie les visiteurs, répond aux questions produit et prend des rendez-vous. Conversion 24/7.",
    outcomes: [
      "Concevoir un parcours conversationnel de vente",
      "Nourrir le chatbot avec vos données produit",
      "Qualifier les visiteurs automatiquement",
      "Intégrer la prise de rendez-vous",
      "Analyser les conversations pour améliorer le taux de conversion",
    ],
    lessons: [
      { id: "23-1", title: "Chatbot commercial vs chatbot support", duration: "10 min", type: "lecture" },
      { id: "23-2", title: "Concevoir le parcours conversationnel", duration: "20 min", type: "exercise" },
      { id: "23-3", title: "Alimenter l'IA avec vos données produit", duration: "22 min", type: "video" },
      { id: "23-4", title: "Qualification et scoring en live", duration: "16 min", type: "exercise" },
      { id: "23-5", title: "Intégrer Calendly / prise de RDV", duration: "14 min", type: "video" },
      { id: "23-6", title: "A/B tester vos scripts de vente", duration: "16 min", type: "exercise" },
      { id: "23-7", title: "Analyser et optimiser les conversations", duration: "12 min", type: "lecture" },
    ],
  },
  {
    slug: "relances-automatiques-ia",
    title: "Relances commerciales automatiques",
    subtitle: "Ne laissez plus jamais un prospect refroidir",
    icon: "🔁",
    level: "Débutant",
    duration: "1h30",
    lessonsCount: 6,
    plan: "starter",
    category: "Ventes & CRM",
    tags: ["Relances", "Follow-up", "Pipeline", "Timing"],
    color: "text-amber-600",
    bgColor: "bg-amber-50 border-amber-100",
    description: "L'IA choisit le bon moment, le bon canal et le bon message pour relancer chaque prospect. Fini les relances oubliées ou trop tard.",
    outcomes: [
      "Configurer des séquences de relance intelligentes",
      "Personnaliser chaque message selon le contexte",
      "Optimiser le timing de chaque relance",
      "Alterner entre email, téléphone et LinkedIn",
      "Savoir quand s'arrêter (stop loss intelligent)",
    ],
    lessons: [
      { id: "24-1", title: "La psychologie du follow-up", duration: "12 min", type: "lecture" },
      { id: "24-2", title: "Séquences multi-canal (email + LinkedIn + tel)", duration: "18 min", type: "exercise" },
      { id: "24-3", title: "Personnalisation IA de chaque relance", duration: "20 min", type: "exercise" },
      { id: "24-4", title: "Le timing optimal selon le segment", duration: "14 min", type: "lecture" },
      { id: "24-5", title: "Workflow de relance dans OpsAI", duration: "18 min", type: "video" },
      { id: "24-6", title: "Analyser ce qui marche (et itérer)", duration: "8 min", type: "exercise" },
    ],
  },
  {
    slug: "personnaliser-offres-ia",
    title: "Personnaliser ses offres commerciales avec l'IA",
    subtitle: "Chaque prospect reçoit LA proposition qui le convertit",
    icon: "🎁",
    level: "Intermédiaire",
    duration: "2h",
    lessonsCount: 7,
    plan: "team",
    category: "Ventes & CRM",
    tags: ["Propositions", "Personnalisation", "Devis", "IA"],
    color: "text-emerald-600",
    bgColor: "bg-emerald-50 border-emerald-100",
    description: "Générez des propositions commerciales personnalisées en 5 minutes au lieu de 2 heures. L'IA adapte le contenu, les prix et les arguments selon le prospect.",
    outcomes: [
      "Créer des templates de proposition dynamiques",
      "Personnaliser automatiquement selon le profil prospect",
      "Adapter le pricing en fonction du segment",
      "Générer des études de cas pertinentes",
      "Tracker l'ouverture et optimiser le closing",
    ],
    lessons: [
      { id: "25-1", title: "L'anatomie d'une offre qui convertit", duration: "14 min", type: "lecture" },
      { id: "25-2", title: "Créer vos templates dynamiques", duration: "22 min", type: "exercise" },
      { id: "25-3", title: "Enrichir le profil prospect par IA", duration: "16 min", type: "video" },
      { id: "25-4", title: "Adapter le discours au segment", duration: "18 min", type: "exercise" },
      { id: "25-5", title: "Pricing dynamique et recommandations", duration: "14 min", type: "lecture" },
      { id: "25-6", title: "Workflow : de la demande à l'envoi", duration: "20 min", type: "video" },
      { id: "25-7", title: "Tracking et optimisation du taux de closing", duration: "16 min", type: "exercise" },
    ],
  },
  {
    slug: "analyse-sentiments-clients",
    title: "Analyse de sentiments clients par IA",
    subtitle: "Comprenez ce que vos clients pensent vraiment",
    icon: "😊",
    level: "Intermédiaire",
    duration: "1h45",
    lessonsCount: 6,
    plan: "team",
    category: "Ventes & CRM",
    tags: ["NLP", "Sentiments", "Feedback", "Satisfaction"],
    color: "text-pink-600",
    bgColor: "bg-pink-50 border-pink-100",
    description: "L'IA analyse les avis, emails et conversations pour détecter le sentiment réel de vos clients. Anticipez le churn et identifiez vos ambassadeurs.",
    outcomes: [
      "Configurer l'analyse de sentiment sur vos canaux",
      "Détecter les clients à risque de churn",
      "Identifier vos ambassadeurs les plus engagés",
      "Analyser les feedbacks produit à l'échelle",
      "Créer des alertes sur les sentiments négatifs",
    ],
    lessons: [
      { id: "26-1", title: "L'analyse de sentiments : comment ça marche", duration: "14 min", type: "lecture" },
      { id: "26-2", title: "Connecter vos sources (avis, emails, chat)", duration: "18 min", type: "video" },
      { id: "26-3", title: "Dashboard de satisfaction en temps réel", duration: "20 min", type: "exercise" },
      { id: "26-4", title: "Détecter les signaux de churn", duration: "16 min", type: "exercise" },
      { id: "26-5", title: "Alertes automatiques et workflows de rétention", duration: "18 min", type: "video" },
      { id: "26-6", title: "Exploiter les insights pour le produit", duration: "9 min", type: "lecture" },
    ],
  },
  {
    slug: "previsions-ventes-ia",
    title: "Prévisions de ventes par IA",
    subtitle: "Prédisez votre CA avec une précision de 90%",
    icon: "📈",
    level: "Avancé",
    duration: "2h",
    lessonsCount: 7,
    plan: "team",
    category: "Ventes & CRM",
    tags: ["Forecast", "Prédiction", "Pipeline", "Data"],
    color: "text-green-600",
    bgColor: "bg-green-50 border-green-100",
    description: "L'IA analyse votre historique, votre pipeline actuel et les tendances pour prédire votre CA à 30, 60 et 90 jours. Fini les forecasts au doigt mouillé.",
    outcomes: [
      "Configurer le modèle de prévision sur vos données",
      "Comprendre les facteurs qui influencent vos ventes",
      "Générer des prévisions à 30/60/90 jours",
      "Identifier les deals à risque dans le pipeline",
      "Présenter les prévisions à votre direction",
    ],
    lessons: [
      { id: "27-1", title: "Pourquoi les forecasts classiques échouent", duration: "12 min", type: "lecture" },
      { id: "27-2", title: "Les données nécessaires (et comment les nettoyer)", duration: "18 min", type: "lecture" },
      { id: "27-3", title: "Configurer le modèle prédictif", duration: "22 min", type: "video" },
      { id: "27-4", title: "Interpréter les résultats", duration: "16 min", type: "exercise" },
      { id: "27-5", title: "Scénarios what-if : tester vos hypothèses", duration: "18 min", type: "exercise" },
      { id: "27-6", title: "Pipeline à risque : détecter et agir", duration: "14 min", type: "exercise" },
      { id: "27-7", title: "Le reporting direction (template)", duration: "20 min", type: "exercise" },
    ],
  },
  {
    slug: "qualification-leads-avancee",
    title: "Qualification de leads avancée",
    subtitle: "Scorez vos leads avec une précision chirurgicale",
    icon: "🏆",
    level: "Avancé",
    duration: "2h15",
    lessonsCount: 7,
    plan: "team",
    category: "Ventes & CRM",
    tags: ["Lead Scoring", "Intent Data", "Enrichissement"],
    color: "text-cyan-600",
    bgColor: "bg-cyan-50 border-cyan-100",
    description: "Allez au-delà du lead scoring basique. Enrichissement de données, intent signals, scoring comportemental et prédictif pour ne travailler que les leads qui vont closer.",
    outcomes: [
      "Construire un modèle de scoring multi-critères",
      "Enrichir vos leads avec des données externes",
      "Détecter les signaux d'intention d'achat",
      "Automatiser le routing vers le bon commercial",
      "Mesurer et améliorer la qualité du scoring",
    ],
    lessons: [
      { id: "28-1", title: "Les limites du lead scoring traditionnel", duration: "12 min", type: "lecture" },
      { id: "28-2", title: "Enrichissement de données par IA", duration: "20 min", type: "video" },
      { id: "28-3", title: "Intent data : les signaux qui comptent", duration: "18 min", type: "lecture" },
      { id: "28-4", title: "Scoring comportemental (tracking + IA)", duration: "22 min", type: "exercise" },
      { id: "28-5", title: "Scoring prédictif : qui va closer ?", duration: "20 min", type: "exercise" },
      { id: "28-6", title: "Routing automatique par score", duration: "14 min", type: "video" },
      { id: "28-7", title: "Itérer et améliorer votre modèle", duration: "19 min", type: "exercise" },
    ],
  },
  {
    slug: "scripts-vente-ia",
    title: "Scripts de vente générés par IA",
    subtitle: "Des scripts de vente qui s'adaptent à chaque prospect",
    icon: "🎙️",
    level: "Intermédiaire",
    duration: "1h45",
    lessonsCount: 6,
    plan: "team",
    category: "Ventes & CRM",
    tags: ["Scripts", "Objections", "Closing", "Persuasion"],
    color: "text-rose-600",
    bgColor: "bg-rose-50 border-rose-100",
    description: "L'IA génère des scripts de vente adaptés au profil, au secteur et aux objections de chaque prospect. Vos commerciaux closent plus avec moins d'effort.",
    outcomes: [
      "Créer des scripts de découverte personnalisés",
      "Générer des réponses aux objections fréquentes",
      "Adapter le pitch au profil psychologique du prospect",
      "A/B tester vos argumentaires",
      "Former les nouveaux commerciaux 3x plus vite",
    ],
    lessons: [
      { id: "29-1", title: "L'art du script adaptatif", duration: "14 min", type: "lecture" },
      { id: "29-2", title: "Créer votre base d'objections et réponses", duration: "20 min", type: "exercise" },
      { id: "29-3", title: "Générer des scripts par persona", duration: "18 min", type: "exercise" },
      { id: "29-4", title: "L'IA comme coach en temps réel", duration: "16 min", type: "video" },
      { id: "29-5", title: "A/B testing des argumentaires", duration: "12 min", type: "exercise" },
      { id: "29-6", title: "Playbook de vente IA : le document final", duration: "15 min", type: "exercise" },
    ],
  },
  {
    slug: "rapports-automatiques",
    title: "Générer des rapports automatiques",
    subtitle: "Vos rapports écrits pendant que vous dormez",
    icon: "📊",
    level: "Intermédiaire",
    duration: "2h15",
    lessonsCount: 8,
    plan: "team",
    category: "Reporting",
    tags: ["Données", "Rapports", "Analytics", "IA"],
    color: "text-blue-600",
    bgColor: "bg-blue-50 border-blue-100",
    description: "Créez des rapports hebdomadaires, mensuels et trimestriels qui se génèrent tout seuls, avec des données à jour et une présentation professionnelle.",
    outcomes: [
      "Automatiser vos rapports hebdomadaires en moins de 2h de setup",
      "Connecter vos sources de données (GA, CRM, finance)",
      "Générer des narratifs IA autour de vos chiffres",
      "Distribuer automatiquement aux bons destinataires",
      "Créer des dashboards IA actualisés en temps réel",
    ],
    lessons: [
      { id: "5-1", title: "Anatomie d'un bon rapport business", duration: "12 min", type: "lecture" },
      { id: "5-2", title: "Connecter vos sources de données", duration: "20 min", type: "video" },
      { id: "5-3", title: "Configurer le workflow weekly_report", duration: "22 min", type: "exercise" },
      { id: "5-4", title: "Écrire les templates narratifs IA", duration: "18 min", type: "exercise" },
      { id: "5-5", title: "Intégrer Google Analytics et CRM", duration: "20 min", type: "video" },
      { id: "5-6", title: "Programmer l'envoi automatique", duration: "10 min", type: "video" },
      { id: "5-7", title: "Rapports trimestriels et annuels", duration: "20 min", type: "lecture" },
      { id: "5-8", title: "Valider la qualité avec un processus de review", duration: "13 min", type: "exercise" },
    ],
  },
  {
    slug: "dashboards-ia-temps-reel",
    title: "Dashboards IA en temps réel",
    subtitle: "Vos KPIs actualisés en permanence, avec alertes IA",
    icon: "📱",
    level: "Intermédiaire",
    duration: "2h",
    lessonsCount: 7,
    plan: "team",
    category: "Reporting",
    tags: ["Dashboard", "Real-time", "KPIs", "Visualisation"],
    color: "text-indigo-600",
    bgColor: "bg-indigo-50 border-indigo-100",
    description: "Construisez des dashboards qui se mettent à jour en temps réel et qui vous alertent quand un KPI dérape. L'IA commente les tendances pour vous.",
    outcomes: [
      "Concevoir un dashboard qui raconte une histoire",
      "Connecter les données en temps réel",
      "Configurer des alertes intelligentes",
      "L'IA qui commente vos tendances chaque matin",
      "Partager les bons KPIs avec les bonnes personnes",
    ],
    lessons: [
      { id: "30-1", title: "Les principes d'un bon dashboard", duration: "14 min", type: "lecture" },
      { id: "30-2", title: "Connecter vos sources en temps réel", duration: "22 min", type: "video" },
      { id: "30-3", title: "Choisir les bons graphiques par KPI", duration: "16 min", type: "lecture" },
      { id: "30-4", title: "Alertes intelligentes : seuils et anomalies", duration: "18 min", type: "exercise" },
      { id: "30-5", title: "Commentaires IA automatiques", duration: "20 min", type: "exercise" },
      { id: "30-6", title: "Distribution et droits d'accès", duration: "10 min", type: "video" },
      { id: "30-7", title: "Dashboard mobile et notifications", duration: "10 min", type: "video" },
    ],
  },
  {
    slug: "analyse-donnees-sans-code",
    title: "Analyser ses données sans coder",
    subtitle: "Posez des questions à vos données en français",
    icon: "🔎",
    level: "Débutant",
    duration: "1h30",
    lessonsCount: 6,
    plan: "starter",
    category: "Reporting",
    tags: ["Data", "No-code", "Questions", "Analyse"],
    color: "text-teal-600",
    bgColor: "bg-teal-50 border-teal-100",
    description: "Plus besoin de SQL ou d'Excel avancé. Posez vos questions en français et l'IA trouve les réponses dans vos données. Pour les non-techniques.",
    outcomes: [
      "Interroger vos données en langage naturel",
      "Créer des analyses en quelques clics",
      "Comprendre les résultats sans jargon statistique",
      "Exporter et partager vos analyses",
      "Automatiser les analyses récurrentes",
    ],
    lessons: [
      { id: "31-1", title: "L'IA comme assistant data (sans code)", duration: "12 min", type: "lecture" },
      { id: "31-2", title: "Connecter votre première source de données", duration: "16 min", type: "video" },
      { id: "31-3", title: "Poser les bonnes questions à vos données", duration: "20 min", type: "exercise" },
      { id: "31-4", title: "Interpréter les résultats en contexte", duration: "14 min", type: "lecture" },
      { id: "31-5", title: "Visualiser et partager vos découvertes", duration: "16 min", type: "exercise" },
      { id: "31-6", title: "Automatiser les analyses régulières", duration: "12 min", type: "exercise" },
    ],
  },
  {
    slug: "reporting-financier-ia",
    title: "Reporting financier automatisé",
    subtitle: "P&L, cash-flow et budgets générés par l'IA",
    icon: "💹",
    level: "Avancé",
    duration: "2h30",
    lessonsCount: 8,
    plan: "team",
    category: "Reporting",
    tags: ["Finance", "P&L", "Budget", "Prévisions"],
    color: "text-emerald-600",
    bgColor: "bg-emerald-50 border-emerald-100",
    description: "Automatisez vos reportings financiers : P&L, suivi de trésorerie, analyse des écarts budgétaires. L'IA détecte les anomalies et génère les commentaires.",
    outcomes: [
      "Automatiser la génération du P&L mensuel",
      "Suivre la trésorerie en temps réel",
      "Détecter les écarts budgétaires automatiquement",
      "Générer les commentaires d'analyse financière",
      "Présenter aux investisseurs avec des données à jour",
    ],
    lessons: [
      { id: "32-1", title: "Les fondamentaux du reporting financier IA", duration: "16 min", type: "lecture" },
      { id: "32-2", title: "Connecter vos données comptables", duration: "20 min", type: "video" },
      { id: "32-3", title: "Automatiser le P&L mensuel", duration: "22 min", type: "exercise" },
      { id: "32-4", title: "Suivi de trésorerie intelligent", duration: "18 min", type: "exercise" },
      { id: "32-5", title: "Analyse des écarts budgétaires", duration: "20 min", type: "video" },
      { id: "32-6", title: "Commentaires IA sur les résultats", duration: "16 min", type: "exercise" },
      { id: "32-7", title: "Prévisions financières à 6 mois", duration: "20 min", type: "exercise" },
      { id: "32-8", title: "Le board deck automatisé (template)", duration: "18 min", type: "exercise" },
    ],
  },
  {
    slug: "veille-concurrentielle-ia",
    title: "Veille concurrentielle automatisée",
    subtitle: "Sachez ce que font vos concurrents avant eux",
    icon: "🕵️",
    level: "Intermédiaire",
    duration: "1h45",
    lessonsCount: 6,
    plan: "team",
    category: "Reporting",
    tags: ["Veille", "Concurrence", "Intelligence", "Marché"],
    color: "text-slate-600",
    bgColor: "bg-slate-50 border-slate-100",
    description: "L'IA surveille vos concurrents 24h/24 : nouveaux produits, recrutements, levées de fonds, avis clients. Rapport de veille hebdomadaire automatique.",
    outcomes: [
      "Configurer la surveillance de vos concurrents clés",
      "Tracker les nouveaux produits et fonctionnalités",
      "Analyser le sentiment sur vos concurrents",
      "Recevoir un briefing hebdomadaire automatique",
      "Détecter les opportunités de marché",
    ],
    lessons: [
      { id: "33-1", title: "Les sources de veille en 2025", duration: "14 min", type: "lecture" },
      { id: "33-2", title: "Configurer le tracking concurrent", duration: "20 min", type: "video" },
      { id: "33-3", title: "Analyse automatique des changements", duration: "18 min", type: "exercise" },
      { id: "33-4", title: "Sentiment et réputation concurrents", duration: "16 min", type: "exercise" },
      { id: "33-5", title: "Le rapport de veille hebdo automatique", duration: "14 min", type: "video" },
      { id: "33-6", title: "De la veille à l'action stratégique", duration: "13 min", type: "lecture" },
    ],
  },
  {
    slug: "kpi-tracking-automatise",
    title: "KPI tracking automatisé",
    subtitle: "Vos indicateurs toujours à jour, sans saisie manuelle",
    icon: "📍",
    level: "Débutant",
    duration: "1h30",
    lessonsCount: 6,
    plan: "starter",
    category: "Reporting",
    tags: ["KPIs", "Tracking", "OKRs", "Performance"],
    color: "text-purple-600",
    bgColor: "bg-purple-50 border-purple-100",
    description: "Définissez vos KPIs une fois, et l'IA les remplit automatiquement depuis vos outils. Plus de saisie manuelle, plus de données périmées.",
    outcomes: [
      "Choisir les KPIs qui comptent vraiment",
      "Connecter chaque KPI à sa source de données",
      "Configurer les mises à jour automatiques",
      "Créer des vues par équipe et par objectif",
      "Alertes quand un KPI dérape",
    ],
    lessons: [
      { id: "34-1", title: "KPIs vs vanity metrics : le tri", duration: "12 min", type: "lecture" },
      { id: "34-2", title: "Mapper KPIs → sources de données", duration: "18 min", type: "exercise" },
      { id: "34-3", title: "Configuration des intégrations", duration: "20 min", type: "video" },
      { id: "34-4", title: "Vues personnalisées par rôle", duration: "14 min", type: "exercise" },
      { id: "34-5", title: "Alertes et notifications intelligentes", duration: "12 min", type: "video" },
      { id: "34-6", title: "Revue de performance hebdomadaire auto", duration: "14 min", type: "exercise" },
    ],
  },
  {
    slug: "data-storytelling-ia",
    title: "Data storytelling avec l'IA",
    subtitle: "Transformez vos données en histoires qui convainquent",
    icon: "📖",
    level: "Avancé",
    duration: "2h",
    lessonsCount: 7,
    plan: "team",
    category: "Reporting",
    tags: ["Storytelling", "Présentation", "Data", "Persuasion"],
    color: "text-fuchsia-600",
    bgColor: "bg-fuchsia-50 border-fuchsia-100",
    description: "Les chiffres seuls ne convainquent personne. Apprenez à utiliser l'IA pour transformer vos données en récits percutants qui font agir votre audience.",
    outcomes: [
      "Structurer un récit data-driven",
      "Laisser l'IA rédiger le narratif autour de vos chiffres",
      "Choisir les visualisations qui frappent",
      "Adapter le storytelling selon l'audience",
      "Créer des présentations qui déclenchent l'action",
    ],
    lessons: [
      { id: "35-1", title: "Pourquoi les chiffres seuls ne suffisent pas", duration: "12 min", type: "lecture" },
      { id: "35-2", title: "Les 5 structures narratives data", duration: "18 min", type: "lecture" },
      { id: "35-3", title: "L'IA comme ghost writer de vos analyses", duration: "22 min", type: "exercise" },
      { id: "35-4", title: "Visualisations qui racontent une histoire", duration: "16 min", type: "exercise" },
      { id: "35-5", title: "Adapter le récit à votre audience", duration: "14 min", type: "lecture" },
      { id: "35-6", title: "De la donnée au slide deck (workflow)", duration: "18 min", type: "video" },
      { id: "35-7", title: "Exercice : transformer un rapport ennuyeux", duration: "20 min", type: "exercise" },
    ],
  },
  {
    slug: "alertes-intelligentes-ia",
    title: "Alertes intelligentes et détection d'anomalies",
    subtitle: "Soyez prévenu avant que le problème n'arrive",
    icon: "🚨",
    level: "Intermédiaire",
    duration: "1h45",
    lessonsCount: 6,
    plan: "team",
    category: "Reporting",
    tags: ["Alertes", "Anomalies", "Monitoring", "Prédictif"],
    color: "text-red-600",
    bgColor: "bg-red-50 border-red-100",
    description: "L'IA surveille vos métriques et vous alerte quand quelque chose d'anormal se produit — avant que ça ne devienne un problème. Fini les mauvaises surprises.",
    outcomes: [
      "Configurer la détection d'anomalies sur vos données",
      "Définir des seuils intelligents (pas de fausses alertes)",
      "Recevoir les alertes sur le bon canal (email, Slack, SMS)",
      "Workflow automatique de résolution",
      "Réduire le temps de réaction de 90%",
    ],
    lessons: [
      { id: "36-1", title: "Alertes classiques vs détection d'anomalies IA", duration: "14 min", type: "lecture" },
      { id: "36-2", title: "Configurer la surveillance de vos métriques", duration: "20 min", type: "video" },
      { id: "36-3", title: "Seuils dynamiques vs statiques", duration: "16 min", type: "exercise" },
      { id: "36-4", title: "Router les alertes au bon endroit", duration: "12 min", type: "video" },
      { id: "36-5", title: "Workflow de résolution automatique", duration: "18 min", type: "exercise" },
      { id: "36-6", title: "Réduire le bruit : éliminer les faux positifs", duration: "15 min", type: "lecture" },
    ],
  },
  {
    slug: "roi-transformation-ia",
    title: "Mesurer le ROI de votre transformation IA",
    subtitle: "Prouver la valeur de l'IA en chiffres",
    icon: "💰",
    level: "Avancé",
    duration: "1h45",
    lessonsCount: 6,
    plan: "team",
    category: "Stratégie",
    tags: ["ROI", "KPIs", "Direction", "Finance"],
    color: "text-green-600",
    bgColor: "bg-green-50 border-green-100",
    description: "Comment démontrer à votre direction et vos investisseurs que l'IA génère un retour concret. Framework de mesure, templates de présentation et benchmarks sectoriels.",
    outcomes: [
      "Calculer précisément le temps économisé par workflow",
      "Convertir les gains de productivité en euros",
      "Présenter le ROI à votre CODIR en 10 slides",
      "Définir les bons KPIs pour votre secteur",
      "Construire un business case pour augmenter votre budget IA",
    ],
    lessons: [
      { id: "6-1", title: "Pourquoi mesurer ? Les enjeux business", duration: "12 min", type: "lecture" },
      { id: "6-2", title: "Les 8 KPIs IA à suivre absolument", duration: "18 min", type: "lecture" },
      { id: "6-3", title: "Calculer le temps économisé (formule)", duration: "20 min", type: "exercise" },
      { id: "6-4", title: "Modèle de présentation CODIR (template)", duration: "22 min", type: "exercise" },
      { id: "6-5", title: "Benchmarks par secteur", duration: "15 min", type: "lecture" },
      { id: "6-6", title: "Construire son business case IA", duration: "18 min", type: "exercise" },
    ],
  },
  {
    slug: "strategie-ia-pme",
    title: "Stratégie IA pour les PME",
    subtitle: "L'IA n'est pas réservée aux grands groupes",
    icon: "🏢",
    level: "Débutant",
    duration: "1h30",
    lessonsCount: 6,
    plan: "free",
    category: "Stratégie",
    tags: ["PME", "Stratégie", "Budget", "Priorités"],
    color: "text-sky-600",
    bgColor: "bg-sky-50 border-sky-100",
    description: "Avec un budget limité et une petite équipe, comment exploiter l'IA ? Ce cours vous donne un plan d'action réaliste pour les PME de 5 à 200 personnes.",
    outcomes: [
      "Prioriser les chantiers IA à fort impact / faible coût",
      "Construire une équipe IA avec les ressources existantes",
      "Choisir entre make, buy et partner",
      "Lancer vos 3 premiers projets IA en 30 jours",
      "Éviter les erreurs spécifiques aux PME",
    ],
    lessons: [
      { id: "37-1", title: "L'avantage des PME face à l'IA", duration: "12 min", type: "lecture" },
      { id: "37-2", title: "Prioriser avec la matrice impact/effort", duration: "18 min", type: "exercise" },
      { id: "37-3", title: "Make, buy or partner ?", duration: "14 min", type: "lecture" },
      { id: "37-4", title: "Constituer son équipe IA (même à 5)", duration: "16 min", type: "exercise" },
      { id: "37-5", title: "Les 3 premiers projets à lancer", duration: "18 min", type: "exercise" },
      { id: "37-6", title: "Pièges courants des PME (et comment les éviter)", duration: "12 min", type: "lecture" },
    ],
  },
  {
    slug: "roadmap-ia-12-mois",
    title: "Construire sa roadmap IA à 12 mois",
    subtitle: "Un plan structuré pour transformer votre entreprise",
    icon: "🗺️",
    level: "Intermédiaire",
    duration: "2h",
    lessonsCount: 7,
    plan: "starter",
    category: "Stratégie",
    tags: ["Roadmap", "Planning", "Transformation", "Milestones"],
    color: "text-amber-600",
    bgColor: "bg-amber-50 border-amber-100",
    description: "De l'audit initial au déploiement à l'échelle : construisez votre roadmap IA trimestre par trimestre, avec des jalons clairs et des quick wins intégrés.",
    outcomes: [
      "Auditer votre maturité IA actuelle",
      "Définir votre vision cible à 12 mois",
      "Planifier par trimestre avec des milestones",
      "Intégrer les quick wins pour maintenir le momentum",
      "Présenter la roadmap à votre direction",
    ],
    lessons: [
      { id: "38-1", title: "L'audit de maturité IA (template)", duration: "18 min", type: "exercise" },
      { id: "38-2", title: "Définir votre vision cible", duration: "16 min", type: "exercise" },
      { id: "38-3", title: "Q1 : les fondations", duration: "18 min", type: "lecture" },
      { id: "38-4", title: "Q2 : les premiers déploiements", duration: "16 min", type: "lecture" },
      { id: "38-5", title: "Q3-Q4 : scaling et optimisation", duration: "18 min", type: "lecture" },
      { id: "38-6", title: "Gérer les imprévus et pivoter", duration: "12 min", type: "lecture" },
      { id: "38-7", title: "Le slide deck roadmap (template)", duration: "22 min", type: "exercise" },
    ],
  },
  {
    slug: "ia-management-equipes",
    title: "Manager une équipe augmentée par l'IA",
    subtitle: "Le nouveau rôle du manager à l'ère de l'IA",
    icon: "👔",
    level: "Intermédiaire",
    duration: "2h",
    lessonsCount: 7,
    plan: "team",
    category: "Stratégie",
    tags: ["Management", "Leadership", "Équipes", "Culture"],
    color: "text-violet-600",
    bgColor: "bg-violet-50 border-violet-100",
    description: "Le rôle du manager change avec l'IA. Apprenez à répartir les tâches humain/IA, développer les compétences de votre équipe et maintenir l'engagement.",
    outcomes: [
      "Définir le partage de tâches humain vs IA",
      "Développer les compétences IA de votre équipe",
      "Maintenir l'engagement quand l'IA prend des tâches",
      "Mesurer la performance d'une équipe augmentée",
      "Gérer les inquiétudes et résistances",
    ],
    lessons: [
      { id: "39-1", title: "Le manager augmenté : nouveau rôle", duration: "14 min", type: "lecture" },
      { id: "39-2", title: "Cartographier les tâches humain vs IA", duration: "20 min", type: "exercise" },
      { id: "39-3", title: "Upskiller votre équipe (plan de formation)", duration: "18 min", type: "exercise" },
      { id: "39-4", title: "Engagement et sens du travail avec l'IA", duration: "14 min", type: "lecture" },
      { id: "39-5", title: "Nouveaux KPIs de performance d'équipe", duration: "16 min", type: "exercise" },
      { id: "39-6", title: "Gérer les résistances concrètement", duration: "16 min", type: "lecture" },
      { id: "39-7", title: "Votre plan d'action managérial", duration: "12 min", type: "exercise" },
    ],
  },
  {
    slug: "scaling-ia-organisation",
    title: "Scaler l'IA dans son organisation",
    subtitle: "De l'expérimentation au déploiement à l'échelle",
    icon: "📐",
    level: "Avancé",
    duration: "2h30",
    lessonsCount: 8,
    plan: "team",
    category: "Stratégie",
    tags: ["Scaling", "Organisation", "Gouvernance", "Centre d'excellence"],
    color: "text-blue-600",
    bgColor: "bg-blue-50 border-blue-100",
    description: "Vous avez validé des POC. Maintenant, comment passer à l'échelle ? Centre d'excellence, gouvernance, budget et gestion du portefeuille de projets IA.",
    outcomes: [
      "Créer votre centre d'excellence IA (CoE)",
      "Mettre en place la gouvernance IA",
      "Gérer un portefeuille de projets IA",
      "Budgétiser et planifier à l'échelle",
      "Mesurer la maturité et progresser",
    ],
    lessons: [
      { id: "40-1", title: "Du POC au production : le fossé", duration: "14 min", type: "lecture" },
      { id: "40-2", title: "Créer votre Centre d'Excellence IA", duration: "22 min", type: "exercise" },
      { id: "40-3", title: "Gouvernance IA : les règles du jeu", duration: "18 min", type: "lecture" },
      { id: "40-4", title: "Portfolio management des projets IA", duration: "20 min", type: "exercise" },
      { id: "40-5", title: "Budgétisation et allocation des ressources", duration: "16 min", type: "exercise" },
      { id: "40-6", title: "Industrialiser les déploiements", duration: "18 min", type: "video" },
      { id: "40-7", title: "Mesurer la maturité IA de l'organisation", duration: "16 min", type: "exercise" },
      { id: "40-8", title: "Plan de scaling à 24 mois", duration: "16 min", type: "exercise" },
    ],
  },
  {
    slug: "benchmark-maturite-ia",
    title: "Benchmarker sa maturité IA",
    subtitle: "Où en êtes-vous vraiment par rapport à votre secteur ?",
    icon: "📏",
    level: "Intermédiaire",
    duration: "1h30",
    lessonsCount: 5,
    plan: "starter",
    category: "Stratégie",
    tags: ["Benchmark", "Maturité", "Évaluation", "Secteur"],
    color: "text-cyan-600",
    bgColor: "bg-cyan-50 border-cyan-100",
    description: "Évaluez objectivement votre niveau de maturité IA par rapport à votre secteur. Identifiez les gaps et priorisez les actions pour progresser.",
    outcomes: [
      "Réaliser votre auto-évaluation de maturité IA",
      "Vous comparer aux benchmarks de votre secteur",
      "Identifier vos points forts et zones de progrès",
      "Prioriser les actions d'amélioration",
      "Générer votre rapport de maturité IA",
    ],
    lessons: [
      { id: "41-1", title: "Les 5 niveaux de maturité IA", duration: "14 min", type: "lecture" },
      { id: "41-2", title: "Auto-évaluation guidée (questionnaire)", duration: "22 min", type: "exercise" },
      { id: "41-3", title: "Benchmarks sectoriels 2025", duration: "16 min", type: "lecture" },
      { id: "41-4", title: "Plan d'action par niveau", duration: "18 min", type: "exercise" },
      { id: "41-5", title: "Votre rapport de maturité (template)", duration: "20 min", type: "exercise" },
    ],
  },
  {
    slug: "ia-innovation-produit",
    title: "IA et innovation produit",
    subtitle: "Créez de meilleurs produits, plus vite, avec l'IA",
    icon: "💡",
    level: "Avancé",
    duration: "2h15",
    lessonsCount: 7,
    plan: "team",
    category: "Stratégie",
    tags: ["Produit", "Innovation", "R&D", "Design"],
    color: "text-orange-600",
    bgColor: "bg-orange-50 border-orange-100",
    description: "L'IA accélère chaque étape du cycle produit : recherche utilisateur, idéation, prototypage, testing. Découvrez comment l'intégrer dans votre processus d'innovation.",
    outcomes: [
      "Analyser les feedbacks utilisateurs à l'échelle",
      "Générer et scorer des idées de features",
      "Accélérer le prototypage avec l'IA",
      "A/B tester plus vite et mieux",
      "Prédire l'adoption de nouvelles features",
    ],
    lessons: [
      { id: "42-1", title: "Le product manager augmenté", duration: "14 min", type: "lecture" },
      { id: "42-2", title: "Analyse des feedbacks à l'échelle", duration: "20 min", type: "exercise" },
      { id: "42-3", title: "Idéation IA : générer et scorer les features", duration: "18 min", type: "exercise" },
      { id: "42-4", title: "Prototypage accéléré par l'IA", duration: "22 min", type: "video" },
      { id: "42-5", title: "Tests utilisateurs assistés par IA", duration: "18 min", type: "exercise" },
      { id: "42-6", title: "Prédire l'adoption avant le lancement", duration: "16 min", type: "lecture" },
      { id: "42-7", title: "Intégrer l'IA dans votre process produit", duration: "17 min", type: "exercise" },
    ],
  },
  {
    slug: "former-equipes-ia",
    title: "Former ses équipes à l'IA",
    subtitle: "Le programme de formation clé en main",
    icon: "🎓",
    level: "Intermédiaire",
    duration: "2h",
    lessonsCount: 7,
    plan: "team",
    category: "Stratégie",
    tags: ["Formation", "Upskilling", "Compétences", "Programme"],
    color: "text-lime-600",
    bgColor: "bg-lime-50 border-lime-100",
    description: "Programme complet pour former vos équipes à l'IA : évaluation des compétences, parcours personnalisés, suivi de progression et certification interne.",
    outcomes: [
      "Évaluer le niveau IA de chaque collaborateur",
      "Construire des parcours de formation personnalisés",
      "Créer des ateliers pratiques engageants",
      "Suivre la progression et mesurer l'impact",
      "Mettre en place une certification interne",
    ],
    lessons: [
      { id: "43-1", title: "Cartographier les compétences IA existantes", duration: "16 min", type: "exercise" },
      { id: "43-2", title: "Définir les parcours par profil métier", duration: "18 min", type: "exercise" },
      { id: "43-3", title: "Concevoir des ateliers pratiques", duration: "20 min", type: "lecture" },
      { id: "43-4", title: "Les outils de formation IA à utiliser", duration: "14 min", type: "lecture" },
      { id: "43-5", title: "Suivi et gamification de la progression", duration: "16 min", type: "video" },
      { id: "43-6", title: "Certification interne : mise en place", duration: "14 min", type: "exercise" },
      { id: "43-7", title: "Mesurer le ROI de la formation IA", duration: "12 min", type: "exercise" },
    ],
  },
  {
    slug: "gouvernance-ia-entreprise",
    title: "Gouvernance IA en entreprise",
    subtitle: "Les règles du jeu pour une IA maîtrisée",
    icon: "🏛️",
    level: "Avancé",
    duration: "2h15",
    lessonsCount: 7,
    plan: "team",
    category: "Stratégie",
    tags: ["Gouvernance", "Politique IA", "Risques", "Comité"],
    color: "text-gray-600",
    bgColor: "bg-gray-50 border-gray-100",
    description: "Mettez en place le cadre de gouvernance IA : comité IA, politique d'usage, gestion des risques et processus de validation. Indispensable pour les entreprises matures.",
    outcomes: [
      "Créer votre comité de gouvernance IA",
      "Rédiger la politique IA de l'entreprise",
      "Mettre en place un processus de validation des projets IA",
      "Gérer les risques IA systématiquement",
      "Assurer la conformité réglementaire continue",
    ],
    lessons: [
      { id: "44-1", title: "Pourquoi la gouvernance IA est incontournable", duration: "14 min", type: "lecture" },
      { id: "44-2", title: "Créer le comité IA (composition et mandat)", duration: "18 min", type: "exercise" },
      { id: "44-3", title: "Rédiger la politique IA (template)", duration: "22 min", type: "exercise" },
      { id: "44-4", title: "Processus de validation des projets IA", duration: "18 min", type: "lecture" },
      { id: "44-5", title: "Registre des risques IA", duration: "20 min", type: "exercise" },
      { id: "44-6", title: "Audits et conformité continue", duration: "16 min", type: "lecture" },
      { id: "44-7", title: "Votre kit de gouvernance complet", duration: "17 min", type: "exercise" },
    ],
  },
];

export const PLAN_ORDER: Record<string, number> = { free: 0, starter: 1, team: 2, enterprise: 3 };

export function getCourseBySlug(slug: string): Course | undefined {
  return COURSES.find((c) => c.slug === slug);
}

export function getCoursesByPlan(plan: string): Course[] {
  const order = { free: 0, starter: 1, team: 2, enterprise: 3 };
  const planLevel = order[plan as keyof typeof order] ?? 0;
  return COURSES.filter((c) => order[c.plan] <= planLevel);
}
